export const queryKeys = {
  cliStatus: ['cli-status'] as const,
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  activity: ['activity'] as const,
  repositories: ['skill-repositories'] as const,
  /** Prefix of every repositoryIndex key, for invalidating them all at once. */
  repositoryIndexes: ['skill-repository-index'] as const,
  repositoryIndex: (id: string) => ['skill-repository-index', id] as const,
  localSkillFolderPreviews: ['local-skill-folder-preview'] as const,
  localSkillFolderPreview: (path: string) => ['local-skill-folder-preview', path] as const,
  installedSkills: (projectId: string | null) => ['installed-skills', projectId] as const,
  /** Prefix of every skill-audit key, so one invalidate refreshes the history and the per-skill lists. */
  skillAudits: ['skill-audits'] as const,
  skillAuditsFor: (skillId: string) => ['skill-audits', skillId] as const,
  skillAuditsLatest: ['skill-audits-latest'] as const,
  auditSourcePreview: (input: string) => ['audit-source-preview', input] as const,
  onDiskSkills: (projectId: string) => ['on-disk-skills', projectId] as const,
  skillUpdates: (projectId: string | null) => ['skill-updates', projectId] as const,
  mcpRepositories: ['mcp-repositories'] as const,
  mcpRepositoryIndex: (id: string) => ['mcp-repository-index', id] as const,
  installedMcpServers: (projectId: string) => ['installed-mcp-servers', projectId] as const,
  toolsStatus: ['tools-status'] as const,
  templates: ['prompt-templates'] as const,
  settings: ['settings'] as const,
  petCustomImages: ['pet-custom-images'] as const,
  petSnooze: ['pet-snooze'] as const,
  usageList: ['usage-list'] as const,
  appVersion: ['app-version'] as const,
  promptHistory: ['prompt-history'] as const,
  promptHistorySearch: (query: string) => ['prompt-history', query] as const,
  // Nested under the same root so invalidating `promptHistory` refreshes it too.
  projectPromptHistory: (projectId: string) => ['prompt-history', 'project', projectId] as const,
  ipGeo: ['ip-geo'] as const,
  topResourceApps: (resource: string) => ['top-resource-apps', resource] as const,
  cliUpdateCheck: (cliId: string, version: string | null) =>
    ['cli-update-check', cliId, version] as const,
  toolUpdateCheck: (toolId: string, version: string | null) =>
    ['tool-update-check', toolId, version] as const,
  projectDrafts: (projectId: string) => ['project-drafts', projectId] as const,
  scheduledTasks: (projectId: string) => ['scheduled-tasks', projectId] as const,
  claudeHooks: (projectId: string) => ['claude-hooks', projectId] as const,
  gitStatus: (projectId: string) => ['git-status', projectId] as const,
  gitFiles: (projectId: string) => ['git-files', projectId] as const,
  gitTags: (projectId: string) => ['git-tags', projectId] as const,
  gitBranchHistory: (projectId: string, branch: string) =>
    ['git-branch-history', projectId, branch] as const,
  githubAccount: ['github-account'] as const,
  githubActivity: ['github-activity'] as const,
  githubNotifications: ['github-notifications'] as const,
  githubActionsActivity: ['github-actions-activity'] as const,
  pipelineStatus: (projectId: string) => ['pipeline-status', projectId] as const,
  /** Branches and tags of a repo, for picking what a manual workflow run should build. */
  pipelineRefs: (repo: string) => ['pipeline-refs', repo] as const,
  appNotifications: ['app-notifications'] as const,
  appNotificationUnread: ['app-notifications-unread'] as const,
  packages: (projectId: string) => ['packages', projectId] as const,
  skillsShSearch: (query: string) => ['skills-sh-search', query] as const,
  skillsShDetail: (id: string) => ['skills-sh-detail', id] as const,
  uiProPrerequisites: ['ui-ux-pro-max-prerequisites'] as const,
  uiProUpdate: ['ui-ux-pro-max-update'] as const,
  remoteSavedServers: ['remote-saved-servers'] as const,
  /** Local LanguageTool install and server state, for Settings and the Tools card. */
  grammarLocalStatus: ['grammar-local-status'] as const,
};
