import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { app } from 'electron';
import { portFilePath } from '../notifications/hookServer';

/**
 * Status hooks for Claude Code sessions started from a workspace tab. They are handed to
 * `claude --settings <file>` at launch instead of being written into the project, so a
 * user's own `.claude/settings.json` is never touched and nothing has to be cleaned up.
 * The script finds its tab through the AGENTMATE_SESSION_ID the terminal put in its env.
 */

/** SessionStart reports the model before the first prompt; the others move the tab's status. */
const HOOK_EVENTS = [
  'SessionStart',
  'UserPromptSubmit',
  'Notification',
  'Stop',
  'SessionEnd',
] as const;

function hooksDir(): string {
  return join(app.getPath('userData'), 'agent-hooks');
}

function scriptContent(portFile: string): string {
  return `#!/usr/bin/env node
// Generated by AgentMate for Workspace tabs. Tells AgentMate what Claude Code is doing so the
// tab can show it (working, waiting for you, finished). Best effort by design: anything that
// goes wrong exits 0 quietly, so Claude Code never reports a hook error because of this.
const http = require('node:http');
const fs = require('node:fs');

process.on('uncaughtException', () => process.exit(0));
process.on('unhandledRejection', () => process.exit(0));

const sessionId = process.env.AGENTMATE_SESSION_ID;
if (!sessionId) process.exit(0);
setTimeout(() => process.exit(0), 4000).unref();

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  input += chunk;
});
process.stdin.on('end', () => {
  let payload = {};
  try {
    payload = JSON.parse(input);
  } catch {}
  let server;
  try {
    server = JSON.parse(fs.readFileSync(${JSON.stringify(portFile)}, 'utf8'));
  } catch {
    process.exit(0);
  }
  if (!server || !server.port || !server.token) process.exit(0);
  const body = JSON.stringify({
    token: server.token,
    sessionId,
    event: payload.hook_event_name,
    notificationType: payload.notification_type,
    message: typeof payload.message === 'string' ? payload.message : undefined,
    // What the tab's tooltip shows. Claude Code keeps both current in a session: the effort
    // in the hook's environment, the model in the transcript (and on SessionStart).
    model: typeof payload.model === 'string' ? payload.model : payload.model && payload.model.id,
    effort: process.env.CLAUDE_EFFORT || undefined,
    transcriptPath: typeof payload.transcript_path === 'string' ? payload.transcript_path : undefined,
  });
  const req = http.request(
    {
      host: '127.0.0.1',
      port: server.port,
      path: '/agent-event',
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      timeout: 2000,
    },
    (res) => {
      res.resume();
      res.on('end', () => process.exit(0));
    },
  );
  req.on('error', () => process.exit(0));
  req.on('timeout', () => req.destroy());
  req.end(body);
});
`;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  const current = await readFile(path, 'utf8').catch(() => null);
  if (current !== content) await writeFile(path, content, 'utf8');
}

let nodeAvailable: Promise<boolean> | null = null;

/** Hooks run the script with `node`; without it on PATH they would only print errors. */
function hasNode(): Promise<boolean> {
  nodeAvailable ??= new Promise((resolve) => {
    execFile('node', ['--version'], { windowsHide: true, timeout: 5000 }, (error) =>
      resolve(!error),
    );
  });
  return nodeAvailable;
}

let prepared: Promise<string | null> | null = null;

/**
 * The settings file to pass to `claude --settings`, written on first use. Null when the hooks
 * cannot run here, in which case the tab falls back to reading status from its output.
 */
export function claudeHookSettingsPath(): Promise<string | null> {
  prepared ??= (async () => {
    if (!(await hasNode())) return null;
    const dir = hooksDir();
    await mkdir(dir, { recursive: true });
    const scriptPath = join(dir, 'agent-event.cjs');
    const settingsPath = join(dir, 'claude-settings.json');
    // Forward slashes survive every shell Claude Code may run a hook through, Git Bash included.
    const command = `node "${scriptPath.replaceAll('\\', '/')}"`;
    const hook = { type: 'command', command, timeout: 5 };
    const hooks = Object.fromEntries(HOOK_EVENTS.map((event) => [event, [{ hooks: [hook] }]]));
    await writeIfChanged(scriptPath, scriptContent(portFilePath()));
    await writeIfChanged(settingsPath, `${JSON.stringify({ hooks }, null, 2)}\n`);
    return settingsPath;
  })().catch(() => {
    prepared = null;
    return null;
  });
  return prepared;
}

/** CLIs whose launches get the status hooks. */
export function supportsStatusHooks(cliId: string): boolean {
  return cliId === 'claude-code';
}
