import {
  createHash,
  createHmac,
  createPrivateKey,
  createPublicKey,
  sign,
  verify,
} from 'node:crypto';
import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import {
  decodeWpFrame,
  decodeWpResponse,
  encodeWpFrame,
  encodeWpMultipart,
  encodeWpResponse,
} from './bundle.js';
import {
  formatWpAuthField,
  parseWpAuthField,
  wpCanonicalPair,
  wpCanonicalRequest,
  wpCanonicalResponse,
} from './canonical.js';
import { formatWpConnectionKey, parseWpConnectionKey } from './connectionKey.js';
import {
  createWpIgnoreRules,
  isValidWpSlug,
  isWpFileItemSlug,
  validateWpItemPath,
} from './pathPolicy.js';
import type { WpRoute } from './protocol.js';

/**
 * The shared vectors (generated by scripts/wordpress-vectors.mjs, also run by the PHP plugin's
 * tests) must keep matching this code. If one of these fails after a change, the protocol changed:
 * regenerate the vectors and make the plugin follow.
 */

const read = (name: string) =>
  JSON.parse(readFileSync(new URL(`./vectors/${name}`, import.meta.url), 'utf8')) as never;

interface Vectors {
  keys: Record<'site' | 'desktop', { seedHex: string; publicKey: string }>;
  ed25519: { seedHex: string; publicKey: string; message: string; signature: string }[];
  canonicalRequest: {
    input: Parameters<typeof wpCanonicalRequest>[0];
    text: string;
    signer: 'desktop';
    signature: string;
  }[];
  canonicalResponse: {
    input: Parameters<typeof wpCanonicalResponse>[0];
    text: string;
    signer: 'site';
    signature: string;
  }[];
  pairProof: {
    input: Parameters<typeof wpCanonicalPair>[0];
    secret: string;
    text: string;
    proof: string;
  }[];
  authField: {
    valid: { value: string; parsed: Parameters<typeof formatWpAuthField>[0] }[];
    invalid: string[];
  };
  connectionKey: {
    now: number;
    valid: { text: string; key: Parameters<typeof formatWpConnectionKey>[0] }[];
    invalid: { text: string; error: string }[];
  };
  paths: { path: string; ok: boolean; reason?: string }[];
  slugs: { slug: string; valid: boolean; fileItem: boolean }[];
  frames: { route: WpRoute; body: unknown; blobsHex: string[]; frameHex: string }[];
  invalidFrames: { why: string; hex: string }[];
  gzip: { plainHex: string; gzipHex: string; gzipSha256: string };
  multipart: {
    auth: string;
    boundary: string;
    gzipHex: string;
    contentType: string;
    bodyHex: string;
  };
  response: {
    canonicalInput: Parameters<typeof wpCanonicalResponse>[0];
    meta: { ts: number; status: number; sig: string };
    frameHex: string;
    payloadHex: string;
    envelopeHex: string;
  };
}

const vectors = read('protocol-v1.json') as Vectors;
const bytes = (hex: string) => new Uint8Array(Buffer.from(hex, 'hex'));
const hexOf = (value: Uint8Array) => Buffer.from(value).toString('hex');

const PKCS8_ED25519 = Buffer.from('302e020100300506032b657004220420', 'hex');
function keyFromSeed(seedHex: string) {
  return createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519, Buffer.from(seedHex, 'hex')]),
    format: 'der',
    type: 'pkcs8',
  });
}
function publicKeyOf(seedHex: string): string {
  const jwk = createPublicKey(keyFromSeed(seedHex)).export({ format: 'jwk' });
  return jwk.x as string;
}
function signWith(seedHex: string, message: string): string {
  return sign(null, Buffer.from(message, 'utf8'), keyFromSeed(seedHex)).toString('base64url');
}
function verifyWith(publicKey: string, message: string, signature: string): boolean {
  const key = createPublicKey({ key: { kty: 'OKP', crv: 'Ed25519', x: publicKey }, format: 'jwk' });
  return verify(null, Buffer.from(message, 'utf8'), key, Buffer.from(signature, 'base64url'));
}

describe('WordPress protocol vectors', () => {
  it('pins Ed25519 key derivation and signatures', () => {
    for (const vector of vectors.ed25519) {
      expect(publicKeyOf(vector.seedHex)).toBe(vector.publicKey);
      expect(signWith(vector.seedHex, vector.message)).toBe(vector.signature);
      expect(verifyWith(vector.publicKey, vector.message, vector.signature)).toBe(true);
    }
  });

  it('builds and signs the canonical request text', () => {
    for (const vector of vectors.canonicalRequest) {
      expect(wpCanonicalRequest(vector.input)).toBe(vector.text);
      expect(signWith(vectors.keys[vector.signer].seedHex, vector.text)).toBe(vector.signature);
    }
  });

  it('builds and signs the canonical response text', () => {
    for (const vector of vectors.canonicalResponse) {
      expect(wpCanonicalResponse(vector.input)).toBe(vector.text);
      expect(signWith(vectors.keys[vector.signer].seedHex, vector.text)).toBe(vector.signature);
    }
  });

  it('builds the pair proof', () => {
    for (const vector of vectors.pairProof) {
      expect(wpCanonicalPair(vector.input)).toBe(vector.text);
      const proof = createHmac('sha256', Buffer.from(vector.secret, 'base64url'))
        .update(vector.text, 'utf8')
        .digest('base64url');
      expect(proof).toBe(vector.proof);
    }
  });

  it('formats and parses am_auth', () => {
    for (const vector of vectors.authField.valid) {
      expect(formatWpAuthField(vector.parsed)).toBe(vector.value);
      expect(parseWpAuthField(vector.value)).toEqual(vector.parsed);
    }
    for (const value of vectors.authField.invalid) expect(parseWpAuthField(value)).toBeNull();
  });

  it('reads connection keys', () => {
    const { now } = vectors.connectionKey;
    for (const vector of vectors.connectionKey.valid) {
      expect(parseWpConnectionKey(vector.text, now)).toEqual({ ok: true, key: vector.key });
    }
    for (const vector of vectors.connectionKey.invalid) {
      expect(parseWpConnectionKey(vector.text, now)).toEqual({ ok: false, error: vector.error });
    }
  });

  it('judges item paths with the pinned reasons', () => {
    for (const vector of vectors.paths) {
      expect(validateWpItemPath(vector.path)).toEqual(
        vector.ok ? { ok: true } : { ok: false, reason: vector.reason },
      );
    }
  });

  it('judges slugs', () => {
    for (const vector of vectors.slugs) {
      expect(isValidWpSlug(vector.slug)).toBe(vector.valid);
      expect(isWpFileItemSlug(vector.slug)).toBe(vector.fileItem);
    }
  });

  it('encodes and decodes frames', () => {
    for (const vector of vectors.frames) {
      const blobs = vector.blobsHex.map(bytes);
      expect(hexOf(encodeWpFrame({ route: vector.route, body: vector.body, blobs }))).toBe(
        vector.frameHex,
      );
      const decoded = decodeWpFrame(bytes(vector.frameHex));
      expect(decoded?.route).toBe(vector.route);
      expect(decoded?.body).toEqual(vector.body);
      expect(decoded?.blobs.map(hexOf)).toEqual(vector.blobsHex);
    }
    for (const vector of vectors.invalidFrames) {
      expect(decodeWpFrame(bytes(vector.hex)), vector.why).toBeNull();
    }
  });

  it('agrees on the gzip sample and its hash', () => {
    const gz = Buffer.from(vectors.gzip.gzipHex, 'hex');
    expect(gunzipSync(gz).toString('hex')).toBe(vectors.gzip.plainHex);
    expect(createHash('sha256').update(gz).digest('hex')).toBe(vectors.gzip.gzipSha256);
  });

  it('writes the multipart body byte for byte', () => {
    const { auth, boundary, gzipHex, contentType, bodyHex } = vectors.multipart;
    const result = encodeWpMultipart(auth, bytes(gzipHex), boundary);
    expect(result.contentType).toBe(contentType);
    expect(hexOf(result.body)).toBe(bodyHex);
    const signed = parseWpAuthField(auth);
    expect(signed?.signature).not.toBeNull();
    const text = wpCanonicalRequest({
      route: '/files/read',
      timestamp: signed?.timestamp ?? 0,
      nonce: signed?.nonce ?? '',
      connectionId: signed?.connectionId ?? null,
      bodySha256: vectors.gzip.gzipSha256,
    });
    expect(verifyWith(vectors.keys.desktop.publicKey, text, signed?.signature ?? '')).toBe(true);
  });

  it('wraps and unwraps a signed response', () => {
    const { canonicalInput, meta, payloadHex, envelopeHex, frameHex } = vectors.response;
    expect(hexOf(encodeWpResponse(meta, bytes(payloadHex)))).toBe(envelopeHex);
    const decoded = decodeWpResponse(bytes(envelopeHex));
    expect(decoded?.meta).toEqual(meta);
    expect(hexOf(decoded?.payload ?? new Uint8Array())).toBe(payloadHex);
    expect(gunzipSync(Buffer.from(payloadHex, 'hex')).toString('hex')).toBe(frameHex);
    expect(createHash('sha256').update(Buffer.from(payloadHex, 'hex')).digest('hex')).toBe(
      canonicalInput.bodySha256,
    );
    expect(
      verifyWith(vectors.keys.site.publicKey, wpCanonicalResponse(canonicalInput), meta.sig),
    ).toBe(true);
  });
});

describe('agent files fixture', () => {
  const fixture = read('agent-files.json') as {
    files: { path: string; expect: 'synced' | 'hardDenied' | 'ignoredUntracked' }[];
  };
  const built = createWpIgnoreRules([]);
  if (!built.ok) throw new Error('default ignore rules must compile');
  const rules = built.rules;

  it('never lets agent or AgentMate files through, and leaves out local clutter', () => {
    for (const file of fixture.files) {
      const verdict = validateWpItemPath(file.path);
      if (file.expect === 'hardDenied') {
        expect(verdict, file.path).toEqual({ ok: false, reason: 'hardDenied' });
        continue;
      }
      expect(verdict, file.path).toEqual({ ok: true });
      expect(rules.excluded(file.path), file.path).toBe(false);
      expect(rules.excludedUnlessTracked(file.path), file.path).toBe(
        file.expect === 'ignoredUntracked',
      );
    }
  });
});
