export const IPC = {
  app: {
    getVersion: 'app:getVersion',
    checkForUpdates: 'app:checkForUpdates',
    downloadUpdate: 'app:downloadUpdate',
    quitAndInstall: 'app:quitAndInstall',
    onUpdateStatus: 'app:onUpdateStatus',
    relaunch: 'app:relaunch',
  },
  backup: {
    export: 'backup:export',
    import: 'backup:import',
  },
  cli: {
    detectAll: 'cli:detectAll',
    getInstallCommand: 'cli:getInstallCommand',
    checkForUpdate: 'cli:checkForUpdate',
    getUpdateCommand: 'cli:getUpdateCommand',
  },
  terminal: {
    create: 'terminal:create',
    write: 'terminal:write',
    resize: 'terminal:resize',
    kill: 'terminal:kill',
    onData: 'terminal:onData',
    onExit: 'terminal:onExit',
  },
  projects: {
    list: 'projects:list',
    create: 'projects:create',
    update: 'projects:update',
    delete: 'projects:delete',
    reorder: 'projects:reorder',
    setPinned: 'projects:setPinned',
    bootstrap: 'projects:bootstrap',
    bootstrapPlan: 'projects:bootstrapPlan',
    pickFolder: 'projects:pickFolder',
    updateNotifications: 'projects:updateNotifications',
    listClaudeHooks: 'projects:listClaudeHooks',
    updateClaudeHook: 'projects:updateClaudeHook',
    deleteClaudeHook: 'projects:deleteClaudeHook',
  },
  notifications: {
    sendTest: 'notifications:sendTest',
    detectChatId: 'notifications:detectChatId',
    onConfirmationForwarded: 'notifications:onConfirmationForwarded',
  },
  skills: {
    listRepositories: 'skills:listRepositories',
    addRepository: 'skills:addRepository',
    removeRepository: 'skills:removeRepository',
    refreshRepository: 'skills:refreshRepository',
    getRepositoryIndex: 'skills:getRepositoryIndex',
    pickLocalRepository: 'skills:pickLocalRepository',
    install: 'skills:install',
    remove: 'skills:remove',
    listInstalled: 'skills:listInstalled',
    searchSkillsSh: 'skills:searchSkillsSh',
    getSkillsShDetail: 'skills:getSkillsShDetail',
    installFromSkillsSh: 'skills:installFromSkillsSh',
  },
  mcp: {
    listRepositories: 'mcp:listRepositories',
    addRepository: 'mcp:addRepository',
    removeRepository: 'mcp:removeRepository',
    refreshRepository: 'mcp:refreshRepository',
    getRepositoryIndex: 'mcp:getRepositoryIndex',
    pickLocalRepository: 'mcp:pickLocalRepository',
    install: 'mcp:install',
    remove: 'mcp:remove',
    listInstalled: 'mcp:listInstalled',
  },
  fs: {
    readFile: 'fs:readFile',
    writeFile: 'fs:writeFile',
    listDirectory: 'fs:listDirectory',
    writeScratchFile: 'fs:writeScratchFile',
    saveFileAs: 'fs:saveFileAs',
  },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
  },
  templates: {
    list: 'templates:list',
    save: 'templates:save',
    delete: 'templates:delete',
  },
  activity: {
    list: 'activity:list',
  },
  system: {
    sample: 'system:sample',
  },
  ipGeo: {
    lookup: 'ipGeo:lookup',
  },
  shell: {
    openExternal: 'shell:openExternal',
    openPath: 'shell:openPath',
  },
  promptHistory: {
    list: 'promptHistory:list',
    search: 'promptHistory:search',
    add: 'promptHistory:add',
    remove: 'promptHistory:remove',
    setTags: 'promptHistory:setTags',
  },
  translate: {
    text: 'translate:text',
  },
  speech: {
    transcribe: 'speech:transcribe',
    getModelState: 'speech:getModelState',
    // main -> renderer: first-run model download progress
    onModelProgress: 'speech:onModelProgress',
  },
  ai: {
    ask: 'ai:ask',
    cancel: 'ai:cancel',
    listOllamaModels: 'ai:listOllamaModels',
    listGeminiModels: 'ai:listGeminiModels',
  },
  projectDrafts: {
    listByProject: 'projectDrafts:listByProject',
    create: 'projectDrafts:create',
    updateStatus: 'projectDrafts:updateStatus',
    remove: 'projectDrafts:remove',
  },
  promptBuildWidget: {
    listWidgets: 'promptBuildWidget:listWidgets',
    getWidget: 'promptBuildWidget:getWidget',
    openWidget: 'promptBuildWidget:openWidget',
    closeWidget: 'promptBuildWidget:closeWidget',
  },
  scheduledTasks: {
    list: 'scheduledTasks:list',
    listByProject: 'scheduledTasks:listByProject',
    createMany: 'scheduledTasks:createMany',
    updateStatus: 'scheduledTasks:updateStatus',
    remove: 'scheduledTasks:remove',
  },
  window: {
    minimize: 'window:minimize',
    maximizeToggle: 'window:maximizeToggle',
    close: 'window:close',
    isMaximized: 'window:isMaximized',
    onMaximizedChange: 'window:onMaximizedChange',
  },
  /** Same shape as `window`, but scoped to the standalone remote session window. */
  remoteSessionWindow: {
    minimize: 'remoteSessionWindow:minimize',
    maximizeToggle: 'remoteSessionWindow:maximizeToggle',
    close: 'remoteSessionWindow:close',
    isMaximized: 'remoteSessionWindow:isMaximized',
    onMaximizedChange: 'remoteSessionWindow:onMaximizedChange',
  },
  remote: {
    getState: 'remote:getState',
    listInterfaces: 'remote:listInterfaces',
    startHost: 'remote:startHost',
    stopHost: 'remote:stopHost',
    generatePairingCode: 'remote:generatePairingCode',
    connect: 'remote:connect',
    /** Same as `connect`, but the resulting session skips capture/WebRTC entirely: file transfer and file-manager browsing only. */
    connectFiles: 'remote:connectFiles',
    disconnect: 'remote:disconnect',
    listSavedServers: 'remote:listSavedServers',
    connectSaved: 'remote:connectSaved',
    connectSavedFiles: 'remote:connectSavedFiles',
    renameSavedServer: 'remote:renameSavedServer',
    removeSavedServer: 'remote:removeSavedServer',
    /** Opens (or focuses) the standalone, resizable session window. */
    openSessionWindow: 'remote:openSessionWindow',
    sendInput: 'remote:sendInput',
    hostTile: 'remote:hostTile',
    setScreenInfo: 'remote:setScreenInfo',
    /** Controller role: reports the video display box's physical-pixel size, debounced on resize. */
    setDisplaySize: 'remote:setDisplaySize',
    sendClipboard: 'remote:sendClipboard',
    sendFile: 'remote:sendFile',
    getFileProgress: 'remote:getFileProgress',
    // Remote file manager: browse/mkdir/delete/rename/upload/download on the peer's filesystem.
    fmRoots: 'remote:fmRoots',
    fmList: 'remote:fmList',
    fmMkdir: 'remote:fmMkdir',
    fmDelete: 'remote:fmDelete',
    fmRename: 'remote:fmRename',
    fmUploadTo: 'remote:fmUploadTo',
    fmDownload: 'remote:fmDownload',
    rtcSignal: 'remote:rtcSignal',
    rtcPeerState: 'remote:rtcPeerState',
    /** Controller role: renderer -> main -> host, WebRTC signaling. */
    clientRtcSignal: 'remote:clientRtcSignal',
    /** Host role: an input event that arrived over the input DataChannel. */
    rtcInput: 'remote:rtcInput',
    /** Host role: renderer asks main to start/stop sampling the OS cursor. */
    setCursorTracking: 'remote:setCursorTracking',
    /** Benchmarking: main-process CPU/memory sample. */
    benchSample: 'remote:benchSample',
    // main -> renderer events
    onState: 'remote:onState',
    onRtcSignal: 'remote:onRtcSignal',
    onRtcPeerGone: 'remote:onRtcPeerGone',
    /** Controller role: WebRTC signaling arriving from the host. */
    onClientRtcSignal: 'remote:onClientRtcSignal',
    /** Host role: sampled OS cursor position, for the cursor DataChannel. */
    onHostCursor: 'remote:onHostCursor',
    onCaptureRefresh: 'remote:onCaptureRefresh',
    onTileDemand: 'remote:onTileDemand',
    onCaptureStart: 'remote:onCaptureStart',
    onCaptureStop: 'remote:onCaptureStop',
    onFrameTile: 'remote:onFrameTile',
    onScreenInfo: 'remote:onScreenInfo',
    /** Host role: a connected peer reported (or updated) its display box size. */
    onPeerDisplaySize: 'remote:onPeerDisplaySize',
    onFileProgress: 'remote:onFileProgress',
    onLog: 'remote:onLog',
  },
  tools: {
    detectAll: 'tools:detectAll',
    getInstallCommand: 'tools:getInstallCommand',
    getUninstallCommand: 'tools:getUninstallCommand',
    getInteractiveLaunchCommand: 'tools:getInteractiveLaunchCommand',
    getDockerCommand: 'tools:getDockerCommand',
  },
  usage: {
    list: 'usage:list',
    get: 'usage:get',
    refresh: 'usage:refresh',
    setProviderConfig: 'usage:setProviderConfig',
    listWidgets: 'usage:listWidgets',
    getWidget: 'usage:getWidget',
    openWidget: 'usage:openWidget',
    closeWidget: 'usage:closeWidget',
    setWidgetStyle: 'usage:setWidgetStyle',
    setWidgetSize: 'usage:setWidgetSize',
    setWidgetMode: 'usage:setWidgetMode',
    setResetAlerts: 'usage:setResetAlerts',
    testResetAlert: 'usage:testResetAlert',
    setThresholdAlerts: 'usage:setThresholdAlerts',
    testThresholdAlert: 'usage:testThresholdAlert',
    // main -> renderer: threshold alert fired but the OS has no notification
    // centre to show it, so the renderer shows a toast instead.
    onThresholdAlert: 'usage:onThresholdAlert',
    // main -> widget window: instance changed, re-read it
    onWidgetUpdated: 'usage:widgetUpdated',
  },
  git: {
    status: 'git:status',
    changeSummary: 'git:changeSummary',
    fetch: 'git:fetch',
    pull: 'git:pull',
    push: 'git:push',
    sync: 'git:sync',
    createBranch: 'git:createBranch',
    commit: 'git:commit',
    tags: 'git:tags',
    createTag: 'git:createTag',
    suggestTag: 'git:suggestTag',
    cancelSuggestTag: 'git:cancelSuggestTag',
    applyVersion: 'git:applyVersion',
    cancelApplyVersion: 'git:cancelApplyVersion',
    suggestBranchName: 'git:suggestBranchName',
    cancelSuggestBranchName: 'git:cancelSuggestBranchName',
    suggestCommitMessage: 'git:suggestCommitMessage',
    cancelSuggestCommitMessage: 'git:cancelSuggestCommitMessage',
    createPullRequest: 'git:createPullRequest',
  },
  packages: {
    list: 'packages:list',
    update: 'packages:update',
    // main -> renderer: per-package progress while an update batch runs
    onUpdateProgress: 'packages:onUpdateProgress',
  },
} as const;
