export const IPC = {
  app: {
    getVersion: 'app:getVersion',
    checkForUpdates: 'app:checkForUpdates',
    downloadUpdate: 'app:downloadUpdate',
    pauseDownload: 'app:pauseDownload',
    quitAndInstall: 'app:quitAndInstall',
    onUpdateStatus: 'app:onUpdateStatus',
    relaunch: 'app:relaunch',
    /** main -> the app window: show this route (a deep link from the pet or a tray click). */
    onNavigate: 'app:navigate',
    /** The renderer collecting a route that arrived while the window was still loading. */
    pendingNavigate: 'app:pendingNavigate',
  },
  backup: {
    export: 'backup:export',
    import: 'backup:import',
  },
  cli: {
    detectAll: 'cli:detectAll',
    getInstallCommand: 'cli:getInstallCommand',
    checkForUpdate: 'cli:checkForUpdate',
    getUpdateCommand: 'cli:getUpdateCommand',
  },
  terminal: {
    create: 'terminal:create',
    write: 'terminal:write',
    resize: 'terminal:resize',
    kill: 'terminal:kill',
    onData: 'terminal:onData',
    onExit: 'terminal:onExit',
  },
  projects: {
    list: 'projects:list',
    create: 'projects:create',
    update: 'projects:update',
    delete: 'projects:delete',
    reorder: 'projects:reorder',
    setPinned: 'projects:setPinned',
    bootstrap: 'projects:bootstrap',
    bootstrapPlan: 'projects:bootstrapPlan',
    pickFolder: 'projects:pickFolder',
    pickIcon: 'projects:pickIcon',
    fetchFavicon: 'projects:fetchFavicon',
    updateNotifications: 'projects:updateNotifications',
    listClaudeHooks: 'projects:listClaudeHooks',
    updateClaudeHook: 'projects:updateClaudeHook',
    deleteClaudeHook: 'projects:deleteClaudeHook',
  },
  notifications: {
    sendTest: 'notifications:sendTest',
    /** Shows a message on the desktop companion, the way the pet hook does. */
    sendPetTest: 'notifications:sendPetTest',
    detectChatId: 'notifications:detectChatId',
    onConfirmationForwarded: 'notifications:onConfirmationForwarded',
  },
  skills: {
    listRepositories: 'skills:listRepositories',
    addRepository: 'skills:addRepository',
    removeRepository: 'skills:removeRepository',
    refreshRepository: 'skills:refreshRepository',
    getRepositoryIndex: 'skills:getRepositoryIndex',
    pickLocalRepository: 'skills:pickLocalRepository',
    previewLocalRepository: 'skills:previewLocalRepository',
    install: 'skills:install',
    remove: 'skills:remove',
    listInstalled: 'skills:listInstalled',
    checkForUpdates: 'skills:checkForUpdates',
    searchSkillsSh: 'skills:searchSkillsSh',
    getSkillsShDetail: 'skills:getSkillsShDetail',
    recordSkillsShInstall: 'skills:recordSkillsShInstall',
    checkUiProPrerequisites: 'skills:checkUiProPrerequisites',
    checkUiProUpdate: 'skills:checkUiProUpdate',
    recordUiProInstall: 'skills:recordUiProInstall',
    // Security audit
    runAudit: 'skills:runAudit',
    cancelAudit: 'skills:cancelAudit',
    /** Reports what a pasted folder path or GitHub address holds, before anything is scanned. */
    previewAuditSource: 'skills:previewAuditSource',
    /** Skills sitting in a scope's agent dirs, whether or not AgentMate installed them. */
    listOnDiskSkills: 'skills:listOnDiskSkills',
    listAudits: 'skills:listAudits',
    latestAuditPerSkill: 'skills:latestAuditPerSkill',
    getAudit: 'skills:getAudit',
    removeAudit: 'skills:removeAudit',
    clearAudits: 'skills:clearAudits',
    // main -> renderer events
    /** A watched local-folder repository changed on disk; payload is the repository id. */
    onRepositoryChanged: 'skills:onRepositoryChanged',
  },
  mcp: {
    listRepositories: 'mcp:listRepositories',
    addRepository: 'mcp:addRepository',
    removeRepository: 'mcp:removeRepository',
    refreshRepository: 'mcp:refreshRepository',
    getRepositoryIndex: 'mcp:getRepositoryIndex',
    pickLocalRepository: 'mcp:pickLocalRepository',
    install: 'mcp:install',
    remove: 'mcp:remove',
    listInstalled: 'mcp:listInstalled',
  },
  fs: {
    readFile: 'fs:readFile',
    writeFile: 'fs:writeFile',
    listDirectory: 'fs:listDirectory',
    writeScratchFile: 'fs:writeScratchFile',
    saveFileAs: 'fs:saveFileAs',
  },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
  },
  templates: {
    list: 'templates:list',
    save: 'templates:save',
    delete: 'templates:delete',
  },
  activity: {
    list: 'activity:list',
  },
  system: {
    sample: 'system:sample',
    topApps: 'system:topApps',
    killProcess: 'system:killProcess',
  },
  ipGeo: {
    lookup: 'ipGeo:lookup',
  },
  shell: {
    openExternal: 'shell:openExternal',
    openPath: 'shell:openPath',
  },
  promptHistory: {
    list: 'promptHistory:list',
    search: 'promptHistory:search',
    add: 'promptHistory:add',
    remove: 'promptHistory:remove',
    setTags: 'promptHistory:setTags',
  },
  translate: {
    text: 'translate:text',
  },
  speech: {
    transcribe: 'speech:transcribe',
    getModelState: 'speech:getModelState',
    // main -> renderer: first-run model download progress
    onModelProgress: 'speech:onModelProgress',
  },
  ai: {
    ask: 'ai:ask',
    cancel: 'ai:cancel',
    listOllamaModels: 'ai:listOllamaModels',
    testOllama: 'ai:testOllama',
    listGeminiModels: 'ai:listGeminiModels',
  },
  projectDrafts: {
    listByProject: 'projectDrafts:listByProject',
    create: 'projectDrafts:create',
    updateStatus: 'projectDrafts:updateStatus',
    remove: 'projectDrafts:remove',
  },
  promptBuildWidget: {
    listWidgets: 'promptBuildWidget:listWidgets',
    getWidget: 'promptBuildWidget:getWidget',
    openWidget: 'promptBuildWidget:openWidget',
    closeWidget: 'promptBuildWidget:closeWidget',
  },
  scheduledTasks: {
    list: 'scheduledTasks:list',
    listByProject: 'scheduledTasks:listByProject',
    createMany: 'scheduledTasks:createMany',
    updateStatus: 'scheduledTasks:updateStatus',
    remove: 'scheduledTasks:remove',
  },
  spellcheck: {
    // main -> renderer: an editable field was right-clicked, open the writing menu
    onShowMenu: 'spellcheck:showMenu',
    addToDictionary: 'spellcheck:addToDictionary',
  },
  grammar: {
    check: 'grammar:check',
    /** Where the local LanguageTool lives, whether Java is there, and what the server is doing. */
    localStatus: 'grammar:localStatus',
    startLocal: 'grammar:startLocal',
    stopLocal: 'grammar:stopLocal',
    /** Opens the tools folder in the OS file manager, creating it first if needed. */
    openToolsFolder: 'grammar:openToolsFolder',
    // main -> renderer: the local server changed state (starting, up, failed)
    onLocalStatus: 'grammar:onLocalStatus',
  },
  window: {
    minimize: 'window:minimize',
    maximizeToggle: 'window:maximizeToggle',
    close: 'window:close',
    isMaximized: 'window:isMaximized',
    onMaximizedChange: 'window:onMaximizedChange',
  },
  /** Same shape as `window`, but scoped to the standalone remote session window. */
  remoteSessionWindow: {
    minimize: 'remoteSessionWindow:minimize',
    maximizeToggle: 'remoteSessionWindow:maximizeToggle',
    close: 'remoteSessionWindow:close',
    isMaximized: 'remoteSessionWindow:isMaximized',
    onMaximizedChange: 'remoteSessionWindow:onMaximizedChange',
  },
  remote: {
    getState: 'remote:getState',
    listInterfaces: 'remote:listInterfaces',
    startHost: 'remote:startHost',
    stopHost: 'remote:stopHost',
    generatePairingCode: 'remote:generatePairingCode',
    connect: 'remote:connect',
    /** Same as `connect`, but the resulting session skips capture/WebRTC entirely: file transfer and file-manager browsing only. */
    connectFiles: 'remote:connectFiles',
    disconnect: 'remote:disconnect',
    listSavedServers: 'remote:listSavedServers',
    connectSaved: 'remote:connectSaved',
    connectSavedFiles: 'remote:connectSavedFiles',
    renameSavedServer: 'remote:renameSavedServer',
    removeSavedServer: 'remote:removeSavedServer',
    /** Opens (or focuses) the standalone, resizable session window. */
    openSessionWindow: 'remote:openSessionWindow',
    sendInput: 'remote:sendInput',
    hostTile: 'remote:hostTile',
    setScreenInfo: 'remote:setScreenInfo',
    /** Controller role: reports the video display box's physical-pixel size, debounced on resize. */
    setDisplaySize: 'remote:setDisplaySize',
    sendClipboard: 'remote:sendClipboard',
    sendFile: 'remote:sendFile',
    getFileProgress: 'remote:getFileProgress',
    // Remote file manager: browse/mkdir/delete/rename/upload/download on the peer's filesystem.
    fmRoots: 'remote:fmRoots',
    fmList: 'remote:fmList',
    fmMkdir: 'remote:fmMkdir',
    fmDelete: 'remote:fmDelete',
    fmRename: 'remote:fmRename',
    fmUploadTo: 'remote:fmUploadTo',
    fmDownload: 'remote:fmDownload',
    rtcSignal: 'remote:rtcSignal',
    rtcPeerState: 'remote:rtcPeerState',
    /** Controller role: renderer -> main -> host, WebRTC signaling. */
    clientRtcSignal: 'remote:clientRtcSignal',
    /** Host role: an input event that arrived over the input DataChannel. */
    rtcInput: 'remote:rtcInput',
    /** Host role: renderer asks main to start/stop sampling the OS cursor. */
    setCursorTracking: 'remote:setCursorTracking',
    /** Benchmarking: main-process CPU/memory sample. */
    benchSample: 'remote:benchSample',
    // main -> renderer events
    onState: 'remote:onState',
    onRtcSignal: 'remote:onRtcSignal',
    onRtcPeerGone: 'remote:onRtcPeerGone',
    /** Controller role: WebRTC signaling arriving from the host. */
    onClientRtcSignal: 'remote:onClientRtcSignal',
    /** Host role: sampled OS cursor position, for the cursor DataChannel. */
    onHostCursor: 'remote:onHostCursor',
    onCaptureRefresh: 'remote:onCaptureRefresh',
    onTileDemand: 'remote:onTileDemand',
    onCaptureStart: 'remote:onCaptureStart',
    onCaptureStop: 'remote:onCaptureStop',
    onFrameTile: 'remote:onFrameTile',
    onScreenInfo: 'remote:onScreenInfo',
    /** Host role: a connected peer reported (or updated) its display box size. */
    onPeerDisplaySize: 'remote:onPeerDisplaySize',
    onFileProgress: 'remote:onFileProgress',
    onLog: 'remote:onLog',
  },
  tools: {
    detectAll: 'tools:detectAll',
    getInstallCommand: 'tools:getInstallCommand',
    checkForUpdate: 'tools:checkForUpdate',
    getUpdateCommand: 'tools:getUpdateCommand',
    getUninstallCommand: 'tools:getUninstallCommand',
    getInteractiveLaunchCommand: 'tools:getInteractiveLaunchCommand',
    getDockerCommand: 'tools:getDockerCommand',
  },
  usage: {
    list: 'usage:list',
    get: 'usage:get',
    refresh: 'usage:refresh',
    setProviderConfig: 'usage:setProviderConfig',
    listWidgets: 'usage:listWidgets',
    getWidget: 'usage:getWidget',
    openWidget: 'usage:openWidget',
    closeWidget: 'usage:closeWidget',
    setWidgetStyle: 'usage:setWidgetStyle',
    setWidgetSize: 'usage:setWidgetSize',
    setWidgetMode: 'usage:setWidgetMode',
    configureWidget: 'usage:configureWidget',
    setResetAlerts: 'usage:setResetAlerts',
    testResetAlert: 'usage:testResetAlert',
    setThresholdAlerts: 'usage:setThresholdAlerts',
    testThresholdAlert: 'usage:testThresholdAlert',
    // main -> renderer: threshold alert fired but the OS has no notification
    // centre to show it, so the renderer shows a toast instead.
    onThresholdAlert: 'usage:onThresholdAlert',
    // main -> widget window: instance changed, re-read it
    onWidgetUpdated: 'usage:widgetUpdated',
  },
  pet: {
    setClickThrough: 'pet:setClickThrough',
    getWorkArea: 'pet:getWorkArea',
    onDisplayChanged: 'pet:displayChanged',
    onSettingsChanged: 'pet:settingsChanged',
    onPipelineMessage: 'pet:pipelineMessage',
    importCustom: 'pet:importCustom',
    removeCustom: 'pet:removeCustom',
    customDataUrls: 'pet:customDataUrls',
    /** Hide the companion for N minutes; it comes back on its own. */
    snooze: 'pet:snooze',
    cancelSnooze: 'pet:cancelSnooze',
    getSnooze: 'pet:getSnooze',
    /** main -> every renderer: the hide started, was cancelled, or ran out. */
    onSnoozeChanged: 'pet:snoozeChanged',
    /**
     * Brings the app window back to the front. Takes an optional route, so the
     * failure the pet just announced can open on the Pipelines page.
     */
    showMainWindow: 'pet:showMainWindow',
  },
  pipelines: {
    status: 'pipelines:status',
    setWatched: 'pipelines:setWatched',
    dashboardActivity: 'pipelines:dashboardActivity',
    runError: 'pipelines:runError',
    refs: 'pipelines:refs',
    dispatch: 'pipelines:dispatch',
    cancelRun: 'pipelines:cancelRun',
  },
  /**
   * The in-app notification inbox. Distinct from the `notifications` group above,
   * which is about sending a notification out (Telegram, the desktop companion).
   */
  appNotifications: {
    list: 'appNotifications:list',
    markRead: 'appNotifications:markRead',
    markAllRead: 'appNotifications:markAllRead',
    remove: 'appNotifications:remove',
    unreadCount: 'appNotifications:unreadCount',
    /** main -> every renderer: something was added to or changed in the inbox. */
    onChanged: 'appNotifications:onChanged',
  },
  git: {
    status: 'git:status',
    listFiles: 'git:listFiles',
    changeSummary: 'git:changeSummary',
    fetch: 'git:fetch',
    pull: 'git:pull',
    push: 'git:push',
    sync: 'git:sync',
    createBranch: 'git:createBranch',
    checkoutBranch: 'git:checkoutBranch',
    setDefaultBranch: 'git:setDefaultBranch',
    renameBranch: 'git:renameBranch',
    deleteBranch: 'git:deleteBranch',
    branchHistory: 'git:branchHistory',
    commit: 'git:commit',
    tags: 'git:tags',
    createTag: 'git:createTag',
    suggestTag: 'git:suggestTag',
    cancelSuggestTag: 'git:cancelSuggestTag',
    applyVersion: 'git:applyVersion',
    cancelApplyVersion: 'git:cancelApplyVersion',
    suggestBranchName: 'git:suggestBranchName',
    cancelSuggestBranchName: 'git:cancelSuggestBranchName',
    suggestCommitMessage: 'git:suggestCommitMessage',
    cancelSuggestCommitMessage: 'git:cancelSuggestCommitMessage',
    createPullRequest: 'git:createPullRequest',
    init: 'git:init',
    githubAccount: 'git:githubAccount',
    githubActivity: 'git:githubActivity',
    githubNotifications: 'git:githubNotifications',
    githubMarkNotificationRead: 'git:githubMarkNotificationRead',
    githubMarkNotificationsRead: 'git:githubMarkNotificationsRead',
    lookupGithubRepo: 'git:lookupGithubRepo',
    createGithubRepo: 'git:createGithubRepo',
    connectRemote: 'git:connectRemote',
    detectRemote: 'git:detectRemote',
  },
  packages: {
    list: 'packages:list',
    update: 'packages:update',
    // main -> renderer: per-package progress while an update batch runs
    onUpdateProgress: 'packages:onUpdateProgress',
  },
} as const;
