import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { PackageUpdateRequest } from '../../shared/apiTypes';
import {
  json,
  type LocalServer,
  startHttpServer,
  tempDir,
  writeTree,
} from '../../test/main/fixtures';
import type { UpdateProgressTick } from './types';

/**
 * pub versions come from three places that can all disagree: the constraint in pubspec.yaml, the
 * resolved version in pubspec.lock, and the pub repository API. The adapter reads the first two
 * with a line reader rather than a YAML parser, so the shapes pub actually writes are what matter
 * here, including the nested and flow forms for a non-hosted dependency.
 */

interface CliCall {
  command: string;
  args: string[];
  cwd: string;
  timeoutMs?: number;
}

interface CliAnswer {
  stdout?: string;
  stderr?: string;
  code?: number;
  notFound?: boolean;
}

const cliState = vi.hoisted(() => ({
  calls: [] as CliCall[],
  handler: (_command: string, _args: string[]): CliAnswer => ({}),
}));

// execUtils is this module's own process boundary; its own tests cover the cmd.exe quoting.
vi.mock('./execUtils', async (importOriginal) => {
  const actual = await importOriginal<typeof import('./execUtils')>();
  return {
    ...actual,
    runCli: async (command: string, args: string[], cwd: string, timeoutMs?: number) => {
      cliState.calls.push({ command, args, cwd, timeoutMs });
      const answer = cliState.handler(command, args);
      if (answer.notFound) throw new actual.CliNotFoundError(`${command} is not available on PATH`);
      return { stdout: answer.stdout ?? '', stderr: answer.stderr ?? '', code: answer.code ?? 0 };
    },
  };
});

const { dartAdapter } = await import('./dartAdapter');

let root = '';
let pub: LocalServer | null = null;
/** Versions the fake pub repository serves, by package name. Null means the socket is dropped. */
let latestByName: Record<string, string | null> = {};

beforeEach(async () => {
  cliState.calls = [];
  cliState.handler = () => ({});
  root = tempDir('agentmate-dart-adapter-');
  latestByName = {};
  pub = await startHttpServer((request, response) => {
    const name = decodeURIComponent(/\/api\/packages\/(.+)$/.exec(request.url ?? '')?.[1] ?? '');
    if (!(name in latestByName)) {
      response.writeHead(404);
      response.end('{"error":{"code":"NotFound"}}');
      return;
    }
    const version = latestByName[name];
    if (version === null) {
      // A dropped socket is what an unreachable mirror looks like to fetch.
      request.socket.destroy();
      return;
    }
    json(response, { name, latest: { version } });
  });
  // Nothing may reach the real pub.dev, including a package with no lock entry.
  vi.stubEnv('PUB_HOSTED_URL', pub.url);
});

afterEach(async () => {
  await pub?.close();
  pub = null;
});

/** A pubspec.lock in the layout pub writes, pointing every package at the local fake. */
function lockFile(packages: Record<string, string>, host = pub?.url ?? ''): string {
  const body = Object.entries(packages)
    .map(
      ([name, version]) => `  ${name}:
    dependency: "direct main"
    description:
      name: ${name}
      sha256: "0000000000000000000000000000000000000000000000000000000000000000"
      url: "${host}"
    source: hosted
    version: "${version}"`,
    )
    .join('\n');
  return `# Generated by pub\npackages:\n${body}\nsdks:\n  dart: ">=3.4.0 <4.0.0"\n`;
}

describe('detect', () => {
  it('is true for a pubspec at the root', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\n' });
    await expect(dartAdapter.detect(root)).resolves.toBe(true);
  });

  it('is true for a nested package in a melos style repo', async () => {
    writeTree(root, { 'packages/core/pubspec.yaml': 'name: core\n' });
    await expect(dartAdapter.detect(root)).resolves.toBe(true);
  });

  it('is false when there is no pubspec anywhere', async () => {
    writeTree(root, { 'README.md': '# nope\n' });
    await expect(dartAdapter.detect(root)).resolves.toBe(false);
  });

  it.each([
    '.dart_tool',
    '.fvm',
    '.pub-cache',
    '.symlinks',
    '.plugin_symlinks',
    'ephemeral',
    'build',
    'Pods',
    'node_modules',
    '.git',
  ])('ignores the copied plugin sources under %s', async (dir) => {
    writeTree(root, { [`${dir}/pubspec.yaml`]: 'name: copied\n' });
    // Flutter and fvm fill these with pubspecs that are not part of the project.
    await expect(dartAdapter.detect(root)).resolves.toBe(false);
  });

  it('stops descending past the depth cap', async () => {
    writeTree(root, { 'a/b/c/d/e/f/pubspec.yaml': 'name: deep\n' });
    await expect(dartAdapter.detect(root)).resolves.toBe(false);
  });
});

describe('pubspec parsing', () => {
  it('reads the plain constraint form and both dependency sections', async () => {
    writeTree(root, {
      'pubspec.yaml': `name: demo
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  http: ^1.2.0
dev_dependencies:
  test: ^1.25.0
`,
      'pubspec.lock': lockFile({ http: '1.2.0', test: '1.25.0' }),
    });
    latestByName = { http: '1.2.0', test: '1.25.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.ecosystem).toBe('dart');
    expect(section.manager).toBe('pub');
    expect(section.packages.map((p) => [p.name, p.isDev])).toEqual([
      ['http', false],
      ['test', true],
    ]);
  });

  it('leaves out SDK packages, which cannot be updated on their own', async () => {
    writeTree(root, {
      'pubspec.yaml': `name: demo
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
`,
      'pubspec.lock': lockFile({ http: '1.2.0' }),
    });
    latestByName = { http: '1.2.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages.map((p) => p.name)).toEqual(['http']);
  });

  it.each([
    ['git', 'git:\n      url: https://github.com/a/b.git\n      ref: main'],
    ['path', 'path: ../sibling'],
  ])('never compares a %s dependency against a registry', async (_source, body) => {
    writeTree(root, {
      'pubspec.yaml': `name: demo
dependencies:
  odd:
    ${body}
`,
      'pubspec.lock': lockFile({ odd: '0.1.0' }),
    });
    latestByName = { odd: '9.9.9' };

    const section = await dartAdapter.listPackages(root);

    // There is no registry version to compare a git or path dependency against.
    expect(section.packages[0]).toMatchObject({ name: 'odd', isOutdated: false });
    expect(pub?.requests).toEqual([]);
  });

  it('reads the flow map form used for a short path dependency', async () => {
    writeTree(root, {
      'pubspec.yaml': `name: demo
dependencies:
  sibling: {path: ../sibling}
`,
      'pubspec.lock': lockFile({ sibling: '0.1.0' }),
    });
    latestByName = { sibling: '9.9.9' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0].isOutdated).toBe(false);
    expect(pub?.requests).toEqual([]);
  });

  it('never moves a custom-hosted dependency, since pub add would change its source', async () => {
    writeTree(root, {
      'pubspec.yaml': `name: demo
dependencies:
  private_pkg:
    hosted:
      name: private_pkg
      url: https://pub.internal.example
    version: ^2.0.0
`,
      'pubspec.lock': lockFile({ private_pkg: '2.0.0' }),
    });
    latestByName = { private_pkg: '3.0.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0]).toMatchObject({ name: 'private_pkg', isOutdated: false });
    expect(pub?.requests).toEqual([]);
  });

  it('ignores comments and blank lines', async () => {
    writeTree(root, {
      'pubspec.yaml': `name: demo

# dependencies we actually want
dependencies:
  http: ^1.2.0  # the only one
  # retired: ^0.1.0
`,
      'pubspec.lock': lockFile({ http: '1.2.0' }),
    });
    latestByName = { http: '1.2.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages.map((p) => p.name)).toEqual(['http']);
    expect(section.packages[0].currentVersion).toBe('1.2.0');
  });

  it('labels a package by its pubspec name, or its folder when it has none', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo_root\ndependencies:\n  http: ^1.2.0\n',
      'packages/core/pubspec.yaml': 'dependencies:\n  http: ^1.2.0\n',
    });

    const section = await dartAdapter.listPackages(root);

    const labels = new Set(section.packages.map((p) => p.projectLabel));
    // A pubspec with no name falls back to its path relative to the scanned folder.
    expect(labels).toEqual(new Set(['demo_root', join('packages', 'core')]));
  });
});

describe('outdated detection', () => {
  function project(constraint = '^1.0.0', locked = '1.0.0'): void {
    writeTree(root, {
      'pubspec.yaml': `name: demo\ndependencies:\n  http: ${constraint}\n`,
      'pubspec.lock': lockFile({ http: locked }),
    });
  }

  it('asks the pub repository API with the documented Accept header', async () => {
    project();
    latestByName = { http: '1.0.0' };

    await dartAdapter.listPackages(root);

    expect(pub?.requests).toHaveLength(1);
    expect(pub?.requests[0].url).toBe('/api/packages/http');
    // The v2 media type is what pub.dev and its mirrors all agree on.
    expect(pub?.requests[0].headers.accept).toBe('application/vnd.pub.v2+json');
  });

  it('uses the host recorded in the lock file, not the default one', async () => {
    project();
    latestByName = { http: '1.0.0' };

    await dartAdapter.listPackages(root);

    // A package resolved from a mirror has to be compared against that mirror.
    expect(pub?.requests).toHaveLength(1);
  });

  it('flags a newer version as an update', async () => {
    project('^1.0.0', '1.0.0');
    latestByName = { http: '1.2.2' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0]).toMatchObject({
      name: 'http',
      currentVersion: '1.0.0',
      latestVersion: '1.2.2',
      isOutdated: true,
      isInstalled: true,
    });
    expect(section.message).toBeNull();
  });

  it('reports the current version when the resolved one is already the latest', async () => {
    project('^1.0.0', '1.2.2');
    latestByName = { http: '1.2.2' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0]).toMatchObject({
      latestVersion: '1.2.2',
      isOutdated: false,
    });
  });

  it('does not offer a downgrade when the lock is ahead of the published latest', async () => {
    project('^2.0.0', '2.0.0');
    latestByName = { http: '1.9.9' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0].isOutdated).toBe(false);
  });

  it('treats a release as newer than its own pre-release', async () => {
    project('^1.0.0', '1.0.0-beta.1');
    latestByName = { http: '1.0.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0]).toMatchObject({ isOutdated: true, latestVersion: '1.0.0' });
  });

  it('does not offer a pre-release over the current release', async () => {
    project('^1.0.0', '1.0.0');
    latestByName = { http: '1.0.0-beta.2' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0].isOutdated).toBe(false);
  });

  it('ignores build metadata when comparing', async () => {
    project('^1.0.0', '1.0.0+5');
    latestByName = { http: '1.0.0+9' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0].isOutdated).toBe(false);
  });

  it('sorts packages by name', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  zeta: ^1.0.0\n  alpha: ^1.0.0\n',
      'pubspec.lock': lockFile({ zeta: '1.0.0', alpha: '1.0.0' }),
    });
    latestByName = { zeta: '1.0.0', alpha: '1.0.0' };

    const section = await dartAdapter.listPackages(root);

    expect(section.packages.map((p) => p.name)).toEqual(['alpha', 'zeta']);
  });
});

describe('lookup failures', () => {
  it('leaves the latest version unknown for a package the host does not have', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  secret_pkg: ^1.0.0\n',
      'pubspec.lock': lockFile({ secret_pkg: '1.0.0' }),
    });

    const section = await dartAdapter.listPackages(root);

    // Null is distinct from "up to date": the row cannot claim either way.
    expect(section.packages[0].latestVersion).toBeNull();
    expect(section.packages[0].isOutdated).toBe(false);
    expect(section.message).toBe('The latest version of 1 package could not be looked up.');
  });

  it('retries once before giving up on a dropped connection', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n',
      'pubspec.lock': lockFile({ http: '1.0.0' }),
    });
    latestByName = { http: null };

    const section = await dartAdapter.listPackages(root);

    // A single dropped connection is common on a slow link, so one retry is worth it.
    expect(pub?.requests).toHaveLength(2);
    expect(section.message).toContain('Could not reach');
    expect(section.message).toContain(pub?.url ?? '');
    expect(section.message).toContain('Refresh to try again.');
  });

  it('stops hammering a host that keeps failing', async () => {
    const names = Array.from({ length: 12 }, (_unused, index) => `pkg_${index}`);
    writeTree(root, {
      'pubspec.yaml': `name: demo\ndependencies:\n${names
        .map((name) => `  ${name}: ^1.0.0`)
        .join('\n')}\n`,
      'pubspec.lock': lockFile(Object.fromEntries(names.map((name) => [name, '1.0.0']))),
    });
    latestByName = Object.fromEntries(names.map((name) => [name, null]));

    const section = await dartAdapter.listPackages(root);

    // Two attempts each would be 24; the host is given up on well before that.
    expect(pub?.requests.length).toBeLessThan(24);
    expect(section.message).toContain('12 packages');
  });

  it('pluralizes the unresolved count', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  a_pkg: ^1.0.0\n  b_pkg: ^1.0.0\n',
      'pubspec.lock': lockFile({ a_pkg: '1.0.0', b_pkg: '1.0.0' }),
    });

    const section = await dartAdapter.listPackages(root);

    expect(section.message).toBe('The latest version of 2 packages could not be looked up.');
  });
});

describe('projects with no lock file', () => {
  it('falls back to the declared constraint and says so', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.2.0\n' });

    const section = await dartAdapter.listPackages(root);

    expect(section.packages[0]).toMatchObject({
      currentVersion: '^1.2.0',
      isInstalled: false,
      isOutdated: false,
    });
    // A caret range is not a version, so there is nothing to compare and nothing to fetch.
    expect(pub?.requests).toEqual([]);
    expect(section.message).toContain('demo has no pubspec.lock');
    expect(section.message).toContain('Run pub get there');
  });

  it('pluralizes across several unlocked sub-projects', async () => {
    writeTree(root, {
      'packages/a/pubspec.yaml': 'name: a\ndependencies:\n  http: ^1.0.0\n',
      'packages/b/pubspec.yaml': 'name: b\ndependencies:\n  http: ^1.0.0\n',
    });

    const section = await dartAdapter.listPackages(root);

    expect(section.message).toContain('a, b have no pubspec.lock');
    expect(section.message).toContain('their versions');
  });

  it('says nothing for an unlocked project with no dependencies at all', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\n' });

    const section = await dartAdapter.listPackages(root);

    expect(section).toMatchObject({ status: 'ok', message: null, packages: [] });
  });

  it('compares an exactly pinned constraint even without a lock file', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: 1.0.0\n' });
    latestByName = { http: '1.2.2' };

    const section = await dartAdapter.listPackages(root);

    // An exact pin is a parseable version, so it can be checked straight away.
    expect(section.packages[0]).toMatchObject({
      currentVersion: '1.0.0',
      latestVersion: '1.2.2',
      isOutdated: true,
    });
  });
});

describe('updatePackages', () => {
  function request(overrides: Partial<PackageUpdateRequest> = {}): PackageUpdateRequest {
    return {
      ecosystem: 'dart',
      name: 'http',
      targetVersion: '1.2.2',
      manifestPath: join(root, 'pubspec.yaml'),
      ...overrides,
    };
  }

  it('uses the dart CLI for a pure dart package', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n' });

    await dartAdapter.updatePackages(root, [request()], () => undefined);

    expect(cliState.calls).toEqual([
      {
        command: 'dart',
        args: ['pub', 'add', 'http:^1.2.2'],
        cwd: root,
        timeoutMs: 5 * 60 * 1000,
      },
    ]);
  });

  it('uses the flutter CLI when the pubspec depends on the flutter SDK', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  flutter:\n    sdk: flutter\n  http: ^1.0.0\n',
    });

    await dartAdapter.updatePackages(root, [request()], () => undefined);

    // `dart pub` in a Flutter package refuses to resolve the flutter SDK dependency.
    expect(cliState.calls[0].command).toBe('flutter');
  });

  it('prefixes a dev dependency so pub keeps it in dev_dependencies', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndev_dependencies:\n  build_runner: ^2.4.0\n',
    });

    await dartAdapter.updatePackages(
      root,
      [request({ name: 'build_runner', targetVersion: '2.4.13' })],
      () => undefined,
    );

    expect(cliState.calls[0].args).toEqual(['pub', 'add', 'dev:build_runner:^2.4.13']);
  });

  it('keeps an exact pin exact instead of widening it to a caret', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: 1.0.0\n' });

    await dartAdapter.updatePackages(root, [request()], () => undefined);

    // Widening a deliberate pin would silently change the project's policy.
    expect(cliState.calls[0].args).toEqual(['pub', 'add', 'http:1.2.2']);
  });

  it('adds every package of one pubspec in a single resolve', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n  path: ^1.8.0\n',
    });

    await dartAdapter.updatePackages(
      root,
      [request(), request({ name: 'path', targetVersion: '1.9.1' })],
      () => undefined,
    );

    expect(cliState.calls).toHaveLength(1);
    expect(cliState.calls[0].args).toEqual(['pub', 'add', 'http:^1.2.2', 'path:^1.9.1']);
  });

  it('runs once per pubspec when the batch spans sub-projects', async () => {
    writeTree(root, {
      'packages/a/pubspec.yaml': 'name: a\ndependencies:\n  http: ^1.0.0\n',
      'packages/b/pubspec.yaml':
        'name: b\ndependencies:\n  flutter:\n    sdk: flutter\n  http: ^1.0.0\n',
    });

    await dartAdapter.updatePackages(
      root,
      [
        request({ manifestPath: join(root, 'packages', 'a', 'pubspec.yaml') }),
        request({ manifestPath: join(root, 'packages', 'b', 'pubspec.yaml') }),
      ],
      () => undefined,
    );

    expect(cliState.calls.map((call) => call.command)).toEqual(['dart', 'flutter']);
    expect(cliState.calls.map((call) => call.cwd)).toEqual([
      join(root, 'packages', 'a'),
      join(root, 'packages', 'b'),
    ]);
  });

  it('assumes flutter when the pubspec cannot be read', async () => {
    await dartAdapter.updatePackages(
      root,
      [request({ manifestPath: join(root, 'missing', 'pubspec.yaml') })],
      () => undefined,
    );

    expect(cliState.calls[0].command).toBe('flutter');
  });

  it('reports progress around the batch', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n' });
    const ticks: UpdateProgressTick[] = [];

    const result = await dartAdapter.updatePackages(
      root,
      [request(), request({ name: 'path' })],
      (tick) => ticks.push(tick),
    );

    expect(result.ok).toBe(true);
    expect(ticks.slice(0, 2).map((t) => t.status)).toEqual(['running', 'running']);
    expect(ticks.slice(2)).toEqual([
      { packageName: 'http', status: 'done', message: undefined, completed: 2, total: 2 },
      { packageName: 'path', status: 'done', message: undefined, completed: 2, total: 2 },
    ]);
  });

  it('explains how to fix a missing SDK rather than leaking the spawn error', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n' });
    cliState.handler = () => ({ notFound: true });

    const result = await dartAdapter.updatePackages(root, [request()], () => undefined);

    expect(result.ok).toBe(false);
    expect(result.results[0].message).toBe(
      'Install the Dart SDK and add it to PATH to update these packages.',
    );
  });

  it('names Flutter in that message for a flutter package', async () => {
    writeTree(root, {
      'pubspec.yaml': 'name: demo\ndependencies:\n  flutter:\n    sdk: flutter\n',
    });
    cliState.handler = () => ({ notFound: true });

    const result = await dartAdapter.updatePackages(root, [request()], () => undefined);

    expect(result.results[0].message).toBe(
      'Install the Flutter SDK and add it to PATH to update these packages.',
    );
  });

  it('surfaces the tail of the CLI output when pub add fails', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n' });
    cliState.handler = () => ({
      code: 65,
      stderr:
        "Because demo depends on http ^1.2.2 which doesn't match any versions, version solving failed.",
    });
    const ticks: UpdateProgressTick[] = [];

    const result = await dartAdapter.updatePackages(root, [request()], (t) => ticks.push(t));

    expect(result.ok).toBe(false);
    expect(result.results[0].message).toContain('version solving failed');
    expect(ticks.at(-1)?.status).toBe('error');
  });

  it('falls back to a generic message when the failing CLI printed nothing', async () => {
    writeTree(root, { 'pubspec.yaml': 'name: demo\ndependencies:\n  http: ^1.0.0\n' });
    cliState.handler = () => ({ code: 2 });

    const result = await dartAdapter.updatePackages(root, [request()], () => undefined);

    expect(result.results[0].message).toBe('dart exited with code 2');
  });

  it('does nothing for an empty batch', async () => {
    await expect(dartAdapter.updatePackages(root, [], () => undefined)).resolves.toEqual({
      ok: true,
      results: [],
    });
    expect(cliState.calls).toEqual([]);
  });
});
