import type { McpRepository } from './types.js';
import { McpRepositoryIndexSchema, type McpRepositoryIndex } from './types.js';

/**
 * Servers bundled from the Bowora MCP directory (https://bowora.com/mcp) as of 2026-07-19,
 * fetched per-server from each server's own /mcp/{slug} detail page. Shipped with the app so
 * the default marketplace listing works offline and never needs a network fetch. Entries
 * without a parsed `command`/`url` had no machine-readable install instructions on the
 * source page — they're still listed for discovery, but need manual setup.
 */
export const BOWORA_MCP_REPOSITORY_ID = 'bowora-directory';

export const bundledMcpDirectory: McpRepositoryIndex = McpRepositoryIndexSchema.parse({
  name: 'Bowora MCP Directory',
  description:
    'Curated MCP servers, bundled with AgentMate for offline browsing and one-click install.',
  servers: [
    {
      id: 'jscpd',
      name: 'Jscpd',
      description:
        'Copy/paste detector for programming source code, supports 223 formats. AI-ready with token-efficient reporter, skill and MCP server.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'kucherenko',
      version: 'latest',
      official: false,
      popularity: 5886,
      websiteUrl: 'https://jscpd.dev/',
      repositoryUrl: 'https://github.com/kucherenko/jscpd',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'mcp-atlassian',
      name: 'MCP Atlassian',
      description: 'MCP server for Atlassian tools (Confluence, Jira)',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'sooperset',
      version: 'latest',
      official: false,
      popularity: 5573,
      websiteUrl: 'https://mcp-atlassian.soomiles.com',
      repositoryUrl: 'https://github.com/sooperset/mcp-atlassian',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'mobile-mcp',
      name: 'Mobile MCP',
      description:
        'Model Context Protocol Server for Mobile Automation and Scraping (iOS, Android, Emulators, Simulators and Real Devices)',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'mobile-next',
      version: 'latest',
      official: false,
      popularity: 5468,
      websiteUrl: 'https://mobilenext.ai',
      repositoryUrl: 'https://github.com/mobile-next/mobile-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'sandbox',
      name: 'Sandbox',
      description:
        'All-in-One Sandbox for AI Agents that combines Browser, Shell, File, MCP and VSCode Server in a single Docker container.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'agent-infra',
      version: 'latest',
      official: false,
      popularity: 5425,
      websiteUrl: 'https://sandbox.agent-infra.com',
      repositoryUrl: 'https://github.com/agent-infra/sandbox',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: '5ire',
      name: '5ire',
      description:
        '5ire is a cross-platform desktop AI assistant, MCP client. It compatible with major service providers,  supports local knowledge base and  tools via model context protocol servers .',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'nanbingxyz',
      version: 'latest',
      official: false,
      popularity: 5277,
      websiteUrl: 'https://5ire.app',
      repositoryUrl: 'https://github.com/nanbingxyz/5ire',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'rocketride-server',
      name: 'Rocketride Server',
      description:
        'High-performance AI pipeline engine with a C++ core and 50+ Python-extensible nodes. Build, debug, and scale LLM workflows with 13+ model providers, 8+ vector databases, and agent orchestration, all from your IDE. Includes VS Code extension, TypeScript/Python SDKs, and Docker deployment.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'rocketride-org',
      version: 'latest',
      official: false,
      popularity: 5209,
      repositoryUrl: 'https://github.com/rocketride-org/rocketride-server',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'linear-mcp',
      name: 'Linear MCP',
      description:
        'Lets agents create issues, search projects, and update Linear tickets while implementing features or triage work.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'linear',
      version: 'latest',
      official: false,
      popularity: 5000,
      websiteUrl: 'https://linear.app',
      repositoryUrl: 'https://github.com/linear/linear-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'awesome-mcp-zh',
      name: 'Awesome MCP ZH',
      description: 'MCP 资源精选， MCP指南，Claude MCP，MCP Servers, MCP Clients',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'yzfly',
      version: 'latest',
      official: false,
      popularity: 7438,
      repositoryUrl: 'https://github.com/yzfly/Awesome-MCP-ZH',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'sentry-mcp',
      name: 'Sentry MCP',
      description:
        'Connects coding agents to Sentry so they can look up issues, stack traces, and project error context while debugging.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'getsentry',
      version: 'latest',
      official: false,
      popularity: 7000,
      websiteUrl: 'https://sentry.io',
      repositoryUrl: 'https://github.com/getsentry/sentry-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'firecrawl-mcp-server',
      name: 'Firecrawl MCP Server',
      description:
        '🔥 Official Firecrawl MCP Server - Adds powerful web scraping and search to Cursor, Claude and any other LLM clients.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'firecrawl',
      version: 'latest',
      official: false,
      popularity: 6960,
      websiteUrl: 'https://firecrawl.dev',
      repositoryUrl: 'https://github.com/firecrawl/firecrawl-mcp-server',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'mcp',
      name: 'MCP',
      description:
        'Browser MCP is a Model Context Provider (MCP) server that allows AI applications to control your browser',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'BrowserMCP',
      version: 'latest',
      official: false,
      popularity: 6831,
      websiteUrl: 'https://browsermcp.io',
      repositoryUrl: 'https://github.com/BrowserMCP/mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'notion-mcp',
      name: 'Notion MCP',
      description:
        'Official-style Notion MCP integration for searching workspaces, reading pages, and updating docs from an agent workflow.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'makenotion',
      version: 'latest',
      official: false,
      popularity: 6500,
      websiteUrl: 'https://www.notion.com',
      repositoryUrl: 'https://github.com/makenotion/notion-mcp-server',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'windows-mcp',
      name: 'Windows MCP',
      description: 'MCP Server for Computer Use in Windows',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'CursorTouch',
      version: 'latest',
      official: false,
      popularity: 6434,
      repositoryUrl: 'https://github.com/CursorTouch/Windows-MCP',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'xcodebuildmcp',
      name: 'XcodeBuildMCP',
      description:
        'A Model Context Protocol (MCP) server and CLI that provides tools for agent use when working on iOS and macOS projects.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'getsentry',
      version: 'latest',
      official: false,
      popularity: 6076,
      websiteUrl: 'https://www.xcodebuildmcp.com',
      repositoryUrl: 'https://github.com/getsentry/XcodeBuildMCP',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'whatsapp-mcp',
      name: 'Whatsapp MCP',
      description: 'WhatsApp MCP server',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'lharries',
      version: 'latest',
      official: false,
      popularity: 5903,
      websiteUrl: 'https://x.com/LukeHarries_/status/1905986562388635913',
      repositoryUrl: 'https://github.com/lharries/whatsapp-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'activepieces',
      name: 'Activepieces',
      description:
        'Open-source no-code automation platform with MCP-compatible integrations for building AI agent workflows.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'activepieces',
      version: 'latest',
      official: false,
      popularity: 23273,
      websiteUrl: 'https://www.activepieces.com',
      repositoryUrl: 'https://github.com/activepieces/activepieces',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'mcp-toolbox',
      name: 'MCP Toolbox',
      description: 'MCP Toolbox for Databases is an open source MCP server for databases.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'googleapis',
      version: 'latest',
      official: false,
      popularity: 15956,
      websiteUrl: 'https://mcp-toolbox.dev/documentation/introduction/',
      repositoryUrl: 'https://github.com/googleapis/mcp-toolbox',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'figma-context-mcp',
      name: 'Figma Context MCP',
      description: 'MCP server to provide Figma layout information to AI coding agents like Cursor',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'GLips',
      version: 'latest',
      official: false,
      popularity: 15402,
      websiteUrl: 'https://www.framelink.ai/',
      repositoryUrl: 'https://github.com/GLips/Figma-Context-MCP',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'casdoor',
      name: 'Casdoor',
      description:
        'An open-source Agent-first Identity and Access Management (IAM) /LLM MCP & agent gateway and auth server with web UI supporting OpenClaw, MCP, OAuth, OIDC, SAML, CAS, LDAP, SCIM, WebAuthn, TOTP, MFA, Face ID, Google Workspace, Azure AD',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'casdoor',
      version: 'latest',
      official: false,
      popularity: 13946,
      websiteUrl: 'https://casdoor.ai',
      repositoryUrl: 'https://github.com/casdoor/casdoor',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'postgres-mcp',
      name: 'PostgreSQL MCP',
      description:
        'A reliable Postgres MCP server for listing schemas, running read queries, and helping agents inspect relational data with explicit connection configuration.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: false,
      popularity: 12000,
      repositoryUrl:
        'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'hexstrike-ai',
      name: 'Hexstrike Ai',
      description:
        'HexStrike AI MCP Agents is an advanced MCP server that lets AI agents (Claude, GPT, Copilot, etc.) autonomously run 150+ cybersecurity tools for automated pentesting, vulnerability discovery, bug bounty automation, and security research. Seamlessly bridge LLMs with real-world offensive security capabilities.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: '0x4m4',
      version: 'latest',
      official: false,
      popularity: 10321,
      websiteUrl: 'https://www.hexstrike.com/',
      repositoryUrl: 'https://github.com/0x4m4/hexstrike-ai',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'mcp-use',
      name: 'MCP Use',
      description:
        'The fullstack MCP framework to develop MCP Apps for ChatGPT / Claude & MCP Servers for AI Agents.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'mcp-use',
      version: 'latest',
      official: false,
      popularity: 10306,
      websiteUrl: 'https://manufact.com',
      repositoryUrl: 'https://github.com/mcp-use/mcp-use',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'supabase-mcp',
      name: 'Supabase MCP',
      description:
        'A popular Supabase MCP server for database inspection, project management, and docs lookup during app development.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'supabase-community',
      version: 'latest',
      official: false,
      popularity: 8500,
      websiteUrl: 'https://supabase.com',
      repositoryUrl: 'https://github.com/supabase-community/supabase-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'desktopcommandermcp',
      name: 'DesktopCommanderMCP',
      description:
        'This is MCP server for Claude that gives it terminal control, file system search and diff file editing capabilities',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'wonderwhy-er',
      version: 'latest',
      official: false,
      popularity: 8297,
      websiteUrl: 'https://desktopcommander.app/',
      repositoryUrl: 'https://github.com/wonderwhy-er/DesktopCommanderMCP',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'webiny-js',
      name: 'Webiny Js',
      description:
        'Open-source, self-hosted CMS platform on AWS serverless (Lambda, DynamoDB, S3). TypeScript framework with multi-tenancy, lifecycle hooks, GraphQL API, and AI-assisted development via MCP server. Built for developers at large organizations.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'webiny',
      version: 'latest',
      official: false,
      popularity: 8014,
      websiteUrl: 'https://www.webiny.com',
      repositoryUrl: 'https://github.com/webiny/webiny-js',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'puppeteer-mcp',
      name: 'Puppeteer MCP',
      description:
        'Gives agents a Puppeteer-backed browser for navigating pages, capturing screenshots, and validating UI flows.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 10000,
      repositoryUrl:
        'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'brave-search-mcp',
      name: 'Brave Search MCP',
      description:
        'Gives agents grounded web results through Brave Search so they can research docs, APIs, and current pages during a task.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 9000,
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'sequential-thinking-mcp',
      name: 'Sequential Thinking MCP',
      description:
        'Helps agents break work into sequenced thoughts, revise earlier steps, and keep long reasoning traces organized.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 8000,
      repositoryUrl:
        'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'sqlite-mcp',
      name: 'SQLite MCP',
      description:
        'Exposes SQLite query and schema tools so agents can inspect and modify local app databases with clear boundaries.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 7500,
      repositoryUrl:
        'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'registry',
      name: 'Registry',
      description: 'A community driven registry service for Model Context Protocol (MCP) servers.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 7019,
      websiteUrl: 'https://github.com/modelcontextprotocol/registry/tree/main/docs',
      repositoryUrl: 'https://github.com/modelcontextprotocol/registry',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'git-mcp',
      name: 'Git MCP',
      description:
        'Useful Git MCP utilities for inspecting commits, diffs, and repository state while agents work on codebases.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 6800,
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/git',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'awesome-mcp-servers',
      name: 'Awesome MCP Servers',
      description: 'A collection of MCP servers.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'punkpeye',
      version: 'latest',
      official: false,
      popularity: 90809,
      websiteUrl: 'https://glama.ai/mcp/servers',
      repositoryUrl: 'https://github.com/punkpeye/awesome-mcp-servers',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'headroom',
      name: 'Headroom',
      description:
        'Compress tool outputs, logs, files, and RAG chunks before they reach the LLM. 20% fewer tokens for coding agents, 60-95% fewer tokens for JSON, same answers. Library, proxy, MCP server.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'headroomlabs-ai',
      version: 'latest',
      official: false,
      popularity: 59284,
      websiteUrl: 'https://headroom-docs.vercel.app/docs',
      repositoryUrl: 'https://github.com/headroomlabs-ai/headroom',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'codebase-memory-mcp',
      name: 'Codebase Memory MCP',
      description:
        'High-performance code intelligence MCP server. Indexes codebases into a persistent knowledge graph — average repo in milliseconds. 158 languages, sub-ms queries, 99% fewer tokens. Single static binary, zero dependencies.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'DeusData',
      version: 'latest',
      official: false,
      popularity: 31724,
      websiteUrl: 'https://deusdata.github.io/codebase-memory-mcp/',
      repositoryUrl: 'https://github.com/DeusData/codebase-memory-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'fastmcp',
      name: 'Fastmcp',
      description: '🚀 The fast, Pythonic way to build MCP servers and clients.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'PrefectHQ',
      version: 'latest',
      official: false,
      popularity: 26217,
      websiteUrl: 'https://gofastmcp.com',
      repositoryUrl: 'https://github.com/PrefectHQ/fastmcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'memory-mcp',
      name: 'Memory MCP',
      description:
        'Stores entities and relations so coding agents can remember project facts across conversations without stuffing everything into the prompt.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 15000,
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'fetch-mcp',
      name: 'Fetch MCP',
      description:
        'Retrieves URLs and returns readable content so agents can inspect documentation and web resources safely.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 11000,
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'chrome-devtools-mcp',
      name: 'Chrome DevTools MCP',
      description:
        'An MCP server from the Chrome DevTools team that gives coding agents page inspection, console, network, performance, and browser interaction capabilities.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'DevOps & Infrastructure', 'Data & Analytics'],
      author: 'ChromeDevTools',
      version: 'latest',
      official: true,
      popularity: 45130,
      websiteUrl: 'https://developer.chrome.com/docs/devtools',
      repositoryUrl: 'https://github.com/ChromeDevTools/chrome-devtools-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['-y', 'chrome-devtools-mcp@latest'],
      },
    },
    {
      id: 'netdata',
      name: 'Netdata',
      description:
        "Netdata's MCP integration gives agents live observability context across systems, containers, services, and applications for investigation and troubleshooting.",
      category: 'DevOps & Infrastructure',
      tags: ['DevOps & Infrastructure', 'Data & Analytics', 'AI & Automation'],
      author: 'netdata',
      version: 'latest',
      official: false,
      popularity: 79480,
      websiteUrl: 'https://www.netdata.cloud',
      repositoryUrl: 'https://github.com/netdata/netdata',
      requiredEnv: [],
      config: {
        transport: 'http',
        url: 'https://mcp.netdata.cloud/mcp',
      },
    },
    {
      id: 'github-mcp-server',
      name: 'GitHub MCP Server',
      description:
        "GitHub's official MCP server connects agents to repository context and common development workflows with configurable toolsets and read-only mode.",
      category: 'Developer Tools',
      tags: ['Developer Tools', 'DevOps & Infrastructure', 'Communication'],
      author: 'github',
      version: 'latest',
      official: true,
      popularity: 39600,
      websiteUrl: 'https://github.com',
      repositoryUrl: 'https://github.com/github/github-mcp-server',
      requiredEnv: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
      config: {
        transport: 'stdio',
        command: 'docker',
        args: [
          'run',
          '-i',
          '--rm',
          '-e',
          'GITHUB_PERSONAL_ACCESS_TOKEN',
          'ghcr.io/github/github-mcp-server',
        ],
      },
    },
    {
      id: 'aws-mcp-servers',
      name: 'AWS MCP Servers',
      description:
        'AWS Labs maintains a collection of MCP servers for architecture, documentation, cost analysis, CDK, Terraform, containers, databases, serverless, and operational workflows.',
      category: 'DevOps & Infrastructure',
      tags: ['DevOps & Infrastructure', 'Developer Tools', 'Business & Finance'],
      author: 'awslabs',
      version: 'latest',
      official: true,
      popularity: 19700,
      websiteUrl: 'https://aws.amazon.com',
      repositoryUrl: 'https://github.com/awslabs/mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'uvx',
        args: ['awslabs.aws-documentation-mcp-server@latest'],
      },
    },
    {
      id: 'playwright-mcp',
      name: 'Playwright MCP',
      description:
        "Microsoft's Playwright MCP server lets agents navigate, inspect, and interact with web pages using deterministic browser automation rather than screenshots alone.",
      category: 'Developer Tools',
      tags: ['Developer Tools', 'AI & Automation', 'Productivity'],
      author: 'microsoft',
      version: 'latest',
      official: true,
      popularity: 45130,
      websiteUrl: 'https://playwright.dev',
      repositoryUrl: 'https://github.com/microsoft/playwright-mcp',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@playwright/mcp'],
      },
    },
    {
      id: 'context7',
      name: 'Context7',
      description:
        'Context7 resolves package identifiers and retrieves up-to-date documentation and code examples so coding agents can work from the right library version.',
      category: 'Developer Tools',
      tags: ['Research & Knowledge', 'Developer Tools', 'AI & Automation'],
      author: 'upstash',
      version: 'latest',
      official: false,
      popularity: 58496,
      websiteUrl: 'https://context7.com',
      repositoryUrl: 'https://github.com/upstash/context7',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@upstash/context7-mcp'],
      },
    },
    {
      id: 'cloudflare',
      name: 'Cloudflare',
      description:
        "Cloudflare's remote MCP servers expose documentation, Workers builds, observability, Radar, browser rendering, and account resources to compatible AI clients.",
      category: 'DevOps & Infrastructure',
      tags: ['DevOps & Infrastructure', 'Developer Tools', 'Security & Privacy'],
      author: 'cloudflare',
      version: 'latest',
      official: true,
      popularity: 22600,
      websiteUrl: 'https://www.cloudflare.com',
      repositoryUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['mcp-remote', 'https://docs.mcp.cloudflare.com/mcp'],
      },
    },
    {
      id: 'markitdown',
      name: 'MarkItDown',
      description:
        "Microsoft's MarkItDown project includes an MCP server for converting PDF, Office, image, audio, HTML, CSV, JSON, and archive files into LLM-friendly Markdown.",
      category: 'Developer Tools',
      tags: ['Developer Tools', 'Content & Writing', 'Data & Analytics', 'Research & Knowledge'],
      author: 'microsoft',
      version: 'latest',
      official: false,
      popularity: 162491,
      websiteUrl: 'https://github.com/microsoft/markitdown',
      repositoryUrl: 'https://github.com/microsoft/markitdown',
      requiredEnv: [],
      config: {
        transport: 'stdio',
      },
    },
    {
      id: 'filesystem',
      name: 'Filesystem',
      description:
        'The official reference MCP server for controlled filesystem access, including reading, writing, moving, searching, and inspecting files inside explicitly allowed directories.',
      category: 'Developer Tools',
      tags: ['Developer Tools', 'Productivity', 'Security & Privacy'],
      author: 'modelcontextprotocol',
      version: 'latest',
      official: true,
      popularity: 78400,
      websiteUrl: 'https://modelcontextprotocol.io',
      repositoryUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
      requiredEnv: [],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed/directory'],
      },
    },
    {
      id: 'stripe',
      name: 'Stripe',
      description:
        "Stripe's agent toolkit includes an MCP server that lets agents inspect and operate Stripe resources while also searching Stripe's developer documentation.",
      category: 'DevOps & Infrastructure',
      tags: ['Business & Finance', 'Developer Tools', 'AI & Automation'],
      author: 'stripe',
      version: 'latest',
      official: true,
      popularity: 11800,
      websiteUrl: 'https://stripe.com',
      repositoryUrl: 'https://github.com/stripe/agent-toolkit',
      requiredEnv: ['STRIPE_SECRET_KEY'],
      config: {
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@stripe/mcp', '--tools=all'],
      },
    },
  ],
});

export const bundledMcpRepository: McpRepository = {
  id: BOWORA_MCP_REPOSITORY_ID,
  name: bundledMcpDirectory.name,
  sourceType: 'bundled',
  source: 'https://bowora.com/mcp',
  addedAt: '2026-07-19T00:00:00.000Z',
  lastRefreshedAt: '2026-07-19T00:00:00.000Z',
};
