import { useState } from 'react';
import { toast } from 'sonner';
import { Link, LinkOff, Send, Upload } from '@/components/icons';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { RemoteScreen } from './RemoteScreen';
import { useRemoteStore } from '@/stores/remoteStore';

export function ControllerPanel(): React.JSX.Element {
  const connection = useRemoteStore((s) => s.state?.connection);
  const [code, setCode] = useState('');
  const [connecting, setConnecting] = useState(false);

  const status = connection?.status ?? 'idle';
  const connected = status === 'connected';
  const active = status === 'connecting' || status === 'connected';

  async function connect(): Promise<void> {
    if (!code.trim()) {
      toast.error('Paste a pairing code first.');
      return;
    }
    setConnecting(true);
    try {
      const result = await window.agentmat.remote.connect(code.trim());
      if (!result.ok) toast.error(result.error ?? 'Could not connect.');
    } finally {
      setConnecting(false);
    }
  }

  if (active) {
    return (
      <Card className="flex min-h-[70vh] flex-col overflow-hidden">
        <CardHeader className="flex flex-row items-center justify-between gap-3 space-y-0 border-b border-border py-3">
          <div className="flex items-center gap-2">
            <Badge variant={connected ? 'success' : 'warning'} className="gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-current" />
              {connected ? 'Connected' : 'Connecting…'}
            </Badge>
            <span className="text-sm font-medium">
              {connection?.remoteDeviceName ?? 'Remote device'}
            </span>
            {connection?.remoteScreen && (
              <span className="text-xs text-muted-foreground">
                {connection.remoteScreen.width}×{connection.remoteScreen.height}
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              disabled={!connected}
              onClick={() => void window.agentmat.remote.sendClipboard()}
            >
              <Send className="h-3.5 w-3.5" /> Clipboard
            </Button>
            <Button
              size="sm"
              variant="secondary"
              disabled={!connected}
              onClick={() => void window.agentmat.remote.sendFile()}
            >
              <Upload className="h-3.5 w-3.5" /> Send file
            </Button>
            <Button size="sm" variant="destructive" onClick={() => void window.agentmat.remote.disconnect()}>
              <LinkOff className="h-3.5 w-3.5" /> Disconnect
            </Button>
          </div>
        </CardHeader>
        <RemoteScreen screen={connection?.remoteScreen ?? null} live={connected} />
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Link className="h-4 w-4 text-primary" /> Connect to a remote machine
        </CardTitle>
        <CardDescription>
          Paste the pairing code generated by the other AgentMate (or the contents of its QR code) to
          take control over your local network.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        <div className="flex flex-col gap-1.5">
          <Label>Pairing code</Label>
          <textarea
            value={code}
            onChange={(e) => setCode(e.target.value)}
            placeholder="AGENTMATE1:…"
            className="h-24 resize-none rounded-md border border-input bg-background p-2 font-mono text-xs"
          />
        </div>
        {status === 'error' && connection?.error && (
          <p className="text-xs text-destructive">{connection.error}</p>
        )}
        <div>
          <Button onClick={() => void connect()} disabled={connecting}>
            <Link className="h-4 w-4" /> {connecting ? 'Connecting…' : 'Connect'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
