import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { CLI_REGISTRY, NOTIFICATION_HOOK_KINDS } from '@agentmat/core';
import type { DetectedClaudeHook, NotificationHookKind, Project } from '@agentmat/core';
import { portFilePath } from './hookServer';

const HOOK_FILE_NAME: Record<NotificationHookKind, string> = {
  completion: 'notify-completion.cjs',
  confirmation: 'notify-confirmation.cjs',
  pet: 'notify-pet.cjs',
};

/** Claude Code hook events that best match each AgentMate notification kind. */
const CLAUDE_EVENT_BY_KIND: Record<NotificationHookKind, string> = {
  completion: 'Stop',
  confirmation: 'Notification',
  pet: 'Stop',
};

const DELIVERY_BY_KIND: Record<NotificationHookKind, string> = {
  completion: 'relay a Telegram message',
  confirmation: 'relay a Telegram message',
  pet: 'speak through the desktop companion',
};

export interface HookInstallStatus {
  scriptPath: string;
  wiredAutomatically: boolean;
}

function hooksDir(projectFolderPath: string): string {
  return join(projectFolderPath, '.agentmate', 'hooks');
}

function scriptPathFor(project: Project, kind: NotificationHookKind): string {
  return join(hooksDir(project.folderPath), HOOK_FILE_NAME[kind]);
}

function generateScriptContent(
  portFile: string,
  projectId: string,
  kind: NotificationHookKind,
): string {
  return `#!/usr/bin/env node
// Generated by AgentMate. Regenerated whenever this project's Notification hooks are saved.
// Pings AgentMate (if running) so it can ${DELIVERY_BY_KIND[kind]} for the "${kind}" event.
// Everything here is best effort: if AgentMate is closed, the port is stale, or the
// notification is switched off, this exits 0 without printing, so the agent's CLI
// never reports a hook error.
const http = require('node:http');
const fs = require('node:fs');

const PORT_FILE = ${JSON.stringify(portFile)};
const PROJECT_ID = ${JSON.stringify(projectId)};
const KIND = ${JSON.stringify(kind)};

// A crash in a hook surfaces as an error in the agent's CLI, so swallow anything unexpected.
process.on('uncaughtException', () => process.exit(0));
process.on('unhandledRejection', () => process.exit(0));

let port;
try {
  port = JSON.parse(fs.readFileSync(PORT_FILE, 'utf-8')).port;
} catch {
  process.exit(0);
}
if (!port) process.exit(0);

const body = JSON.stringify({ projectId: PROJECT_ID, kind: KIND });
try {
  const req = http.request(
    {
      host: '127.0.0.1',
      port,
      path: '/hook',
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      timeout: 3000,
    },
    (res) => res.resume(),
  );
  req.on('error', () => {});
  req.on('timeout', () => req.destroy());
  req.write(body);
  req.end();
} catch {
  process.exit(0);
}
setTimeout(() => process.exit(0), 3500).unref();
`;
}

/** A single `{ type, command, ... }` hook entry. May carry extra fields (args, timeout, env, …) we pass through untouched. */
interface ClaudeHookEntry {
  type?: string;
  command?: string;
  [key: string]: unknown;
}
interface ClaudeHookGroup {
  matcher?: string;
  hooks: ClaudeHookEntry[];
}
interface ClaudeSettings {
  hooks?: Record<string, ClaudeHookGroup[]>;
  [key: string]: unknown;
}

/** Claude Code reads hooks from both of these project-level files and merges them. */
const CLAUDE_SETTINGS_FILES = ['settings.json', 'settings.local.json'] as const;
type ClaudeSettingsFile = (typeof CLAUDE_SETTINGS_FILES)[number];

function settingsPathFor(
  projectFolderPath: string,
  file: ClaudeSettingsFile = 'settings.json',
): string {
  return join(projectFolderPath, '.claude', file);
}

async function readClaudeSettings(path: string): Promise<ClaudeSettings> {
  try {
    return JSON.parse(await readFile(path, 'utf-8')) as ClaudeSettings;
  } catch {
    return {};
  }
}

function isOurGroup(group: ClaudeHookGroup, marker: string): boolean {
  return group.hooks.length > 0 && group.hooks.every((h) => (h.command ?? '').includes(marker));
}

/**
 * Merges (or removes) our hook command into `.claude/settings.json` without touching any
 * other hooks the user may have configured. Matched by the script's own filename, so this
 * is idempotent whether called on save, disable, or agent switch.
 */
async function setClaudeCodeHook(
  projectFolderPath: string,
  kind: NotificationHookKind,
  scriptPath: string | null,
): Promise<void> {
  const settingsPath = settingsPathFor(projectFolderPath);
  const settings = await readClaudeSettings(settingsPath);
  const event = CLAUDE_EVENT_BY_KIND[kind];
  const marker = HOOK_FILE_NAME[kind];

  const hooks: Record<string, ClaudeHookGroup[]> = { ...(settings.hooks ?? {}) };
  const remaining = (hooks[event] ?? []).filter((group) => !isOurGroup(group, marker));

  if (scriptPath) {
    hooks[event] = [
      ...remaining,
      { hooks: [{ type: 'command', command: `node ${JSON.stringify(scriptPath)}` }] },
    ];
  } else if (remaining.length > 0) {
    hooks[event] = remaining;
  } else {
    delete hooks[event];
  }

  const next: ClaudeSettings = { ...settings };
  if (Object.keys(hooks).length > 0) {
    next.hooks = hooks;
  } else {
    delete next.hooks;
  }

  await mkdir(join(projectFolderPath, '.claude'), { recursive: true });
  await writeFile(settingsPath, JSON.stringify(next, null, 2), 'utf-8');
}

/**
 * Applies a project's saved notification hook settings to disk: writes (or removes) the
 * relay script for each enabled/disabled hook, and automatically wires Claude Code's own
 * hook config when that's the selected agent. Other agents don't have a known hook schema
 * AgentMate can safely edit, so callers should point users at the generated script to wire
 * up manually.
 */
export async function installProjectNotificationHooks(
  project: Project,
): Promise<Record<NotificationHookKind, HookInstallStatus | null>> {
  const portFile = portFilePath();
  const result: Record<NotificationHookKind, HookInstallStatus | null> = {
    completion: null,
    confirmation: null,
    pet: null,
  };

  for (const kind of NOTIFICATION_HOOK_KINDS) {
    const hook = project.notifications[kind];
    const scriptPath = scriptPathFor(project, kind);

    if (hook.enabled) {
      await mkdir(hooksDir(project.folderPath), { recursive: true });
      await writeFile(scriptPath, generateScriptContent(portFile, project.id, kind), 'utf-8');
      const wiredAutomatically = hook.cliId === 'claude-code';
      await setClaudeCodeHook(project.folderPath, kind, wiredAutomatically ? scriptPath : null);
      result[kind] = { scriptPath, wiredAutomatically };
    } else {
      await unlink(scriptPath).catch(() => {
        // script may already be gone; nothing to clean up
      });
      await setClaudeCodeHook(project.folderPath, kind, null);
    }
  }

  return result;
}

function isAgentMateCommand(command: string): boolean {
  return Object.values(HOOK_FILE_NAME).some((marker) => command.includes(marker));
}

/**
 * Lists every hook command found in this project's `.claude/settings.json` and
 * `.claude/settings.local.json` (Claude Code reads and merges both), including ones AgentMate
 * didn't create. Each entry's `id` encodes where it lives (`file:event:groupIndex:hookIndex`)
 * so it can be targeted by {@link updateClaudeHook} / {@link deleteClaudeHook} on a later read.
 */
/**
 * Attributes a hook to a specific agent. These hooks all live in Claude Code's settings, so they
 * belong to Claude Code unless the command clearly shells out to another known agent (e.g. `codex`
 * or `gemini`), in which case we attribute it there. Defaults to `claude-code`.
 */
function identifyHookCli(command: string): string {
  for (const cli of CLI_REGISTRY) {
    if (cli.id === 'claude-code') continue;
    for (const exe of cli.executableNames) {
      // Match the executable as a standalone token so e.g. "gemini" doesn't hit inside "geminid".
      if (new RegExp(`(?<![\\w-])${escapeRegExp(exe)}(?![\\w-])`).test(command)) {
        return cli.id;
      }
    }
  }
  return 'claude-code';
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export async function listClaudeHooks(projectFolderPath: string): Promise<DetectedClaudeHook[]> {
  const entries: DetectedClaudeHook[] = [];

  for (const file of CLAUDE_SETTINGS_FILES) {
    const settings = await readClaudeSettings(settingsPathFor(projectFolderPath, file));
    for (const [event, groups] of Object.entries(settings.hooks ?? {})) {
      groups.forEach((group, groupIndex) => {
        group.hooks.forEach((hook, hookIndex) => {
          entries.push({
            id: `${file}:${event}:${groupIndex}:${hookIndex}`,
            event,
            matcher: group.matcher,
            hook,
            managedByAgentMate: isAgentMateCommand(hook.command ?? ''),
            // These all live in Claude Code's settings, so they're Claude Code hooks unless the
            // command clearly shells out to another agent.
            cliId: identifyHookCli(hook.command ?? ''),
          });
        });
      });
    }
  }

  return entries;
}

function parseHookId(id: string): {
  file: ClaudeSettingsFile;
  event: string;
  groupIndex: number;
  hookIndex: number;
} {
  const [file, event, groupIndexStr, hookIndexStr] = id.split(':');
  const groupIndex = Number(groupIndexStr);
  const hookIndex = Number(hookIndexStr);
  if (
    !CLAUDE_SETTINGS_FILES.includes(file as ClaudeSettingsFile) ||
    !event ||
    Number.isNaN(groupIndex) ||
    Number.isNaN(hookIndex)
  ) {
    throw new Error(`Invalid hook id: ${id}`);
  }
  return { file: file as ClaudeSettingsFile, event, groupIndex, hookIndex };
}

/** Replaces the matcher and/or raw hook body of a single entry previously returned by {@link listClaudeHooks}. */
export async function updateClaudeHook(
  projectFolderPath: string,
  id: string,
  updates: { matcher?: string; hook: Record<string, unknown> },
): Promise<void> {
  const { file, event, groupIndex, hookIndex } = parseHookId(id);
  const settingsPath = settingsPathFor(projectFolderPath, file);
  const settings = await readClaudeSettings(settingsPath);

  const group = settings.hooks?.[event]?.[groupIndex];
  if (!group || !group.hooks[hookIndex]) throw new Error(`Hook ${id} not found`);

  group.hooks[hookIndex] = updates.hook;
  if (updates.matcher) {
    group.matcher = updates.matcher;
  } else {
    delete group.matcher;
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
}

/** Removes a single hook entry previously returned by {@link listClaudeHooks}, cleaning up empty groups/events. */
export async function deleteClaudeHook(projectFolderPath: string, id: string): Promise<void> {
  const { file, event, groupIndex, hookIndex } = parseHookId(id);
  const settingsPath = settingsPathFor(projectFolderPath, file);
  const settings = await readClaudeSettings(settingsPath);

  const groups = settings.hooks?.[event];
  const group = groups?.[groupIndex];
  if (!groups || !group || !group.hooks[hookIndex]) throw new Error(`Hook ${id} not found`);

  group.hooks.splice(hookIndex, 1);
  if (group.hooks.length === 0) {
    groups.splice(groupIndex, 1);
  }
  if (groups.length === 0) {
    delete settings.hooks?.[event];
  }
  if (settings.hooks && Object.keys(settings.hooks).length === 0) {
    delete settings.hooks;
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
}
