import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { DetectedClaudeHook, NotificationHookKind, Project } from '@agentmat/core';
import { portFilePath } from './hookServer';

const HOOK_FILE_NAME: Record<NotificationHookKind, string> = {
  completion: 'notify-completion.cjs',
  confirmation: 'notify-confirmation.cjs',
};

/** Claude Code hook events that best match each AgentMate notification kind. */
const CLAUDE_EVENT_BY_KIND: Record<NotificationHookKind, string> = {
  completion: 'Stop',
  confirmation: 'Notification',
};

export interface HookInstallStatus {
  scriptPath: string;
  wiredAutomatically: boolean;
}

function hooksDir(projectFolderPath: string): string {
  return join(projectFolderPath, '.agentmate', 'hooks');
}

function scriptPathFor(project: Project, kind: NotificationHookKind): string {
  return join(hooksDir(project.folderPath), HOOK_FILE_NAME[kind]);
}

function generateScriptContent(
  portFile: string,
  projectId: string,
  kind: NotificationHookKind,
): string {
  return `#!/usr/bin/env node
// Generated by AgentMate — regenerated whenever this project's Notification hooks are saved.
// Pings AgentMate (if running) so it can relay a Telegram message for the "${kind}" event.
const http = require('node:http');
const fs = require('node:fs');

const PORT_FILE = ${JSON.stringify(portFile)};
const PROJECT_ID = ${JSON.stringify(projectId)};
const KIND = ${JSON.stringify(kind)};

let port;
try {
  port = JSON.parse(fs.readFileSync(PORT_FILE, 'utf-8')).port;
} catch {
  process.exit(0);
}

const body = JSON.stringify({ projectId: PROJECT_ID, kind: KIND });
const req = http.request(
  {
    host: '127.0.0.1',
    port,
    path: '/hook',
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    timeout: 3000,
  },
  (res) => res.resume(),
);
req.on('error', () => {});
req.on('timeout', () => req.destroy());
req.write(body);
req.end();
setTimeout(() => process.exit(0), 3500).unref();
`;
}

interface ClaudeHookEntry {
  type: 'command';
  command: string;
}
interface ClaudeHookGroup {
  matcher?: string;
  hooks: ClaudeHookEntry[];
}
interface ClaudeSettings {
  hooks?: Record<string, ClaudeHookGroup[]>;
  [key: string]: unknown;
}

async function readClaudeSettings(path: string): Promise<ClaudeSettings> {
  try {
    return JSON.parse(await readFile(path, 'utf-8')) as ClaudeSettings;
  } catch {
    return {};
  }
}

function isOurGroup(group: ClaudeHookGroup, marker: string): boolean {
  return group.hooks.length > 0 && group.hooks.every((h) => h.command.includes(marker));
}

/**
 * Merges (or removes) our hook command into `.claude/settings.json` without touching any
 * other hooks the user may have configured. Matched by the script's own filename, so this
 * is idempotent whether called on save, disable, or agent switch.
 */
async function setClaudeCodeHook(
  projectFolderPath: string,
  kind: NotificationHookKind,
  scriptPath: string | null,
): Promise<void> {
  const settingsPath = join(projectFolderPath, '.claude', 'settings.json');
  const settings = await readClaudeSettings(settingsPath);
  const event = CLAUDE_EVENT_BY_KIND[kind];
  const marker = HOOK_FILE_NAME[kind];

  const hooks: Record<string, ClaudeHookGroup[]> = { ...(settings.hooks ?? {}) };
  const remaining = (hooks[event] ?? []).filter((group) => !isOurGroup(group, marker));

  if (scriptPath) {
    hooks[event] = [...remaining, { hooks: [{ type: 'command', command: `node ${JSON.stringify(scriptPath)}` }] }];
  } else if (remaining.length > 0) {
    hooks[event] = remaining;
  } else {
    delete hooks[event];
  }

  const next: ClaudeSettings = { ...settings };
  if (Object.keys(hooks).length > 0) {
    next.hooks = hooks;
  } else {
    delete next.hooks;
  }

  await mkdir(join(projectFolderPath, '.claude'), { recursive: true });
  await writeFile(settingsPath, JSON.stringify(next, null, 2), 'utf-8');
}

/**
 * Applies a project's saved notification hook settings to disk: writes (or removes) the
 * relay script for each enabled/disabled hook, and automatically wires Claude Code's own
 * hook config when that's the selected agent. Other agents don't have a known hook schema
 * AgentMate can safely edit, so callers should point users at the generated script to wire
 * up manually.
 */
export async function installProjectNotificationHooks(
  project: Project,
): Promise<Record<NotificationHookKind, HookInstallStatus | null>> {
  const portFile = portFilePath();
  const result: Record<NotificationHookKind, HookInstallStatus | null> = {
    completion: null,
    confirmation: null,
  };

  for (const kind of ['completion', 'confirmation'] as const) {
    const hook = project.notifications[kind];
    const scriptPath = scriptPathFor(project, kind);

    if (hook.enabled) {
      await mkdir(hooksDir(project.folderPath), { recursive: true });
      await writeFile(scriptPath, generateScriptContent(portFile, project.id, kind), 'utf-8');
      const wiredAutomatically = hook.cliId === 'claude-code';
      await setClaudeCodeHook(project.folderPath, kind, wiredAutomatically ? scriptPath : null);
      result[kind] = { scriptPath, wiredAutomatically };
    } else {
      await unlink(scriptPath).catch(() => {});
      await setClaudeCodeHook(project.folderPath, kind, null);
    }
  }

  return result;
}

function settingsPathFor(projectFolderPath: string): string {
  return join(projectFolderPath, '.claude', 'settings.json');
}

function isAgentMateCommand(command: string): boolean {
  return Object.values(HOOK_FILE_NAME).some((marker) => command.includes(marker));
}

/**
 * Lists every hook command found in this project's `.claude/settings.json`, including ones
 * AgentMate didn't create. Each entry's `id` encodes its position (`event:groupIndex:hookIndex`)
 * so it can be targeted by {@link updateClaudeHook} / {@link deleteClaudeHook} on the same read.
 */
export async function listClaudeHooks(projectFolderPath: string): Promise<DetectedClaudeHook[]> {
  const settings = await readClaudeSettings(settingsPathFor(projectFolderPath));
  const entries: DetectedClaudeHook[] = [];

  for (const [event, groups] of Object.entries(settings.hooks ?? {})) {
    groups.forEach((group, groupIndex) => {
      group.hooks.forEach((hook, hookIndex) => {
        entries.push({
          id: `${event}:${groupIndex}:${hookIndex}`,
          event,
          matcher: group.matcher,
          command: hook.command,
          managedByAgentMate: isAgentMateCommand(hook.command),
        });
      });
    });
  }

  return entries;
}

function parseHookId(id: string): { event: string; groupIndex: number; hookIndex: number } {
  const [event, groupIndexStr, hookIndexStr] = id.split(':');
  const groupIndex = Number(groupIndexStr);
  const hookIndex = Number(hookIndexStr);
  if (!event || Number.isNaN(groupIndex) || Number.isNaN(hookIndex)) {
    throw new Error(`Invalid hook id: ${id}`);
  }
  return { event, groupIndex, hookIndex };
}

/** Edits the matcher and/or command of a single hook entry previously returned by {@link listClaudeHooks}. */
export async function updateClaudeHook(
  projectFolderPath: string,
  id: string,
  updates: { matcher?: string; command: string },
): Promise<void> {
  const settingsPath = settingsPathFor(projectFolderPath);
  const settings = await readClaudeSettings(settingsPath);
  const { event, groupIndex, hookIndex } = parseHookId(id);

  const group = settings.hooks?.[event]?.[groupIndex];
  const hook = group?.hooks[hookIndex];
  if (!group || !hook) throw new Error(`Hook ${id} not found`);

  hook.command = updates.command;
  if (updates.matcher) {
    group.matcher = updates.matcher;
  } else {
    delete group.matcher;
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
}

/** Removes a single hook entry previously returned by {@link listClaudeHooks}, cleaning up empty groups/events. */
export async function deleteClaudeHook(projectFolderPath: string, id: string): Promise<void> {
  const settingsPath = settingsPathFor(projectFolderPath);
  const settings = await readClaudeSettings(settingsPath);
  const { event, groupIndex, hookIndex } = parseHookId(id);

  const groups = settings.hooks?.[event];
  const group = groups?.[groupIndex];
  if (!groups || !group || !group.hooks[hookIndex]) throw new Error(`Hook ${id} not found`);

  group.hooks.splice(hookIndex, 1);
  if (group.hooks.length === 0) {
    groups.splice(groupIndex, 1);
  }
  if (groups.length === 0) {
    delete settings.hooks?.[event];
  }
  if (settings.hooks && Object.keys(settings.hooks).length === 0) {
    delete settings.hooks;
  }

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
}
